import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execa } from "execa";
import { describe, expect, it } from "vitest";
import type { BundlerAdapter } from "../src/bundler.js";
import {
  build,
  type Config,
  dev,
  type Plugin,
  prepareFrameworkBuild,
} from "../src/index.js";

const repoRoot = path.resolve(process.cwd(), "../..");
const generatedRouteTypesSource = [
  "/* eslint-disable */",
  "// This file is generated by evjs. Do not edit it directly.",
  "export {};",
].join("\n");

async function createProject() {
  const cwd = await fs.promises.mkdtemp(path.join(os.tmpdir(), "evjs-"));
  await fs.promises.writeFile(
    path.join(cwd, "index.html"),
    '<div id="app"></div>',
    "utf-8",
  );
  return cwd;
}

async function createWorkspaceProject() {
  const root = path.join(repoRoot, "test-results");
  await fs.promises.mkdir(root, { recursive: true });
  const cwd = await fs.promises.mkdtemp(path.join(root, "evjs-"));
  await fs.promises.writeFile(
    path.join(cwd, "index.html"),
    '<div id="app"></div>',
    "utf-8",
  );
  return cwd;
}

async function writeRouteTypeCheckTsConfig(cwd: string) {
  await fs.promises.mkdir(path.join(cwd, "src"), { recursive: true });
  await fs.promises.writeFile(
    path.join(cwd, "src/evjs-test-env.d.ts"),
    [
      'declare module "react-server-dom-webpack/client" {',
      "  export function createFromFetch(",
      "    fetchPromise: Promise<Response>,",
      "    options?: { moduleBaseURL?: string },",
      "  ): unknown;",
      "}",
      "",
    ].join("\n"),
    "utf-8",
  );
  await fs.promises.writeFile(
    path.join(cwd, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ESNext",
          jsx: "react-jsx",
          module: "ESNext",
          moduleResolution: "Bundler",
          strict: true,
          skipLibCheck: true,
          noEmit: true,
          types: ["node"],
          paths: {
            "@evjs/client": ["../../packages/client/src/index.ts"],
            "@evjs/shared": ["../../packages/shared/src/index.ts"],
          },
        },
        include: ["src"],
      },
      null,
      2,
    ),
    "utf-8",
  );
}

function createMockBundler(
  events: string[],
): BundlerAdapter<Record<string, never>> {
  return {
    name: "mock",
    async build({ config, plan }) {
      events.push("bundler.build");
      events.push(
        `bundler.entries:${plan.entries.map((entry) => entry.name).join(",")}`,
      );
      if (config.serverEnabled) {
        events.push(
          `bundler.endpoint:${config.server.functionRuntime.endpoint}`,
        );
      }
      return {
        clientEntryAssets: {
          main: { js: ["main.js"], css: [] },
        },
        firstClientEntryAssets: { js: ["main.js"], css: [] },
        serverEntryAssets: {
          server: { js: ["server.js"], css: [] },
        },
        serverEntry: config.serverEnabled ? "server.js" : undefined,
        serverAssets: config.serverEnabled
          ? { js: ["server.js"], css: [] }
          : undefined,
      };
    },
    async dev() {
      events.push("bundler.dev");
    },
  };
}

function createRouteUpdateBundler(
  cwd: string,
  events: string[],
  routeLiteral: string,
): BundlerAdapter<Record<string, never>> {
  return {
    name: "mock",
    async build() {
      return {};
    },
    async dev({ plan }) {
      recordPagesAppRoutes("initial", plan.entries[0]?.metadata, events);
      return {
        async updatePlan(update) {
          recordPagesAppRoutes(
            "changed",
            update.entries.changed[0]?.metadata,
            events,
          );
          const routeTypes = await fs.promises.readFile(
            path.join(cwd, "src/evjs-route-types.d.ts"),
            "utf-8",
          );
          events.push(
            `types:${routeTypes.includes(JSON.stringify(routeLiteral))}`,
          );
          process.emit("SIGINT");
        },
      };
    },
  };
}

function recordPagesAppRoutes(
  label: string,
  metadata:
    | NonNullable<import("@evjs/shared/manifest").BuildEntry["metadata"]>
    | undefined,
  events: string[],
): void {
  if (metadata?.type !== "pages-app") return;
  events.push(
    `${label}:${metadata.routes.map((route) => route.path).join(",")}`,
  );
}

describe("prepareFrameworkBuild", () => {
  it("rejects mismatched command and mode options", async () => {
    const cwd = await createProject();

    await expect(
      prepareFrameworkBuild(
        { server: false },
        { cwd, command: "build", mode: "development" },
      ),
    ).rejects.toThrow(
      'prepareFrameworkBuild command "build" must use mode "production"',
    );
  });

  it("prepares a framework graph and build plan without a bundler adapter", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const plugin: Plugin<Record<string, never>> = {
      name: "prepare-core",
      config(config, ctx) {
        events.push(`config:${ctx.command}`);
        return config;
      },
      setup(ctx) {
        expect(ctx.config.bundler).toBeUndefined();
        ctx.addWatchFile("./framework-extra.json");
        events.push(`setup:${ctx.command}`);
        return {
          commandStart() {
            events.push("commandStart");
          },
          buildStart() {
            events.push("buildStart");
          },
          appGraph(graph) {
            events.push(`appGraph:${Object.keys(graph.apps).join(",")}`);
          },
          buildPlan(plan) {
            events.push(
              `buildPlan:${plan.entries.map((entry) => entry.name).join(",")}`,
            );
          },
          dispose() {
            events.push("dispose");
          },
        };
      },
    };

    const prepared = await prepareFrameworkBuild(
      {
        server: false,
        plugins: [plugin],
      },
      { cwd },
    );

    expect(prepared.config.serverEnabled).toBe(false);
    expect(prepared.graph.apps.default).toEqual({
      id: "default",
      entry: "./src/main.tsx",
      html: "./index.html",
    });
    expect(prepared.plan.entries).toEqual([
      {
        name: "main",
        import: "./src/main.tsx",
        environment: "client",
        runtime: "browser",
        kind: "app-client",
        owner: { appId: "default" },
      },
    ]);
    expect(prepared.pluginWatchFiles).toEqual([
      path.join(cwd, "framework-extra.json"),
    ]);
    expect(events).toEqual([
      "config:build",
      "setup:build",
      "commandStart",
      "buildStart",
      "appGraph:default",
      "buildPlan:main",
    ]);

    await prepared.dispose();
    await prepared.dispose();

    expect(events).toEqual([
      "config:build",
      "setup:build",
      "commandStart",
      "buildStart",
      "appGraph:default",
      "buildPlan:main",
      "dispose",
    ]);
  });
});

describe("build", () => {
  it("requires a bundler from config or options", async () => {
    const cwd = await createProject();
    await expect(build({ server: false }, { cwd })).rejects.toThrow(
      "No bundler configured",
    );
  });

  it("disposes prepared plugin hooks when build stops before bundler execution", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "dist"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "dist/.evjs-dev.lock"),
      JSON.stringify({
        command: "dev",
        distDir: "dist",
        pid: process.pid,
        startedAt: new Date().toISOString(),
      }),
      "utf-8",
    );
    const events: string[] = [];

    await expect(
      build(
        {
          server: false,
          plugins: [
            {
              name: "cleanup",
              setup() {
                events.push("setup");
                return {
                  dispose() {
                    events.push("dispose");
                  },
                };
              },
            },
          ],
        },
        { cwd, bundler: createMockBundler(events) },
      ),
    ).rejects.toThrow('Cannot write to "dist"');

    expect(events).toEqual(["setup", "dispose"]);
  });

  it("runs framework orchestration around the injected bundler", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    const plugin: Plugin<Record<string, never>> = {
      name: "records-lifecycle",
      setup(ctx) {
        expect(ctx.config.bundler?.name).toBe("mock");
        events.push(`setup:${ctx.mode}`);
        return {
          commandStart(ctx) {
            events.push(`commandStart:${ctx.command}`);
          },
          buildStart() {
            events.push("buildStart");
          },
          appGraph(graph) {
            events.push(`appGraph:${Object.keys(graph.apps).join(",")}`);
          },
          buildPlan(plan) {
            events.push(
              `buildPlan:${plan.entries.map((entry) => entry.name).join(",")}`,
            );
          },
          buildOutput(output) {
            events.push(`buildOutput:${Object.keys(output.assets).join(",")}`);
            output.apps.default.assets.js = ["main.patched.js"];
          },
          buildEnd(result) {
            events.push(`buildEnd:${result.output.apps.default.assets.js[0]}`);
          },
          dispose(ctx) {
            events.push(`dispose:${ctx.mode}`);
          },
        };
      },
    };

    await build(
      { server: false, plugins: [plugin] },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "setup:production",
      "commandStart:build",
      "buildStart",
      "appGraph:default",
      "buildPlan:main",
      "bundler.build",
      "bundler.entries:main",
      "buildOutput:main",
      "buildEnd:main.patched.js",
      "dispose:production",
    ]);
  });

  it("builds a pages SPA without a user entry file", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await build(
      {
        server: false,
        plugins: [
          {
            name: "records-pages-plan",
            setup() {
              return {
                buildPlan(plan) {
                  const entry = plan.entries[0];
                  events.push(`entry:${entry?.import}`);
                  events.push(`metadata:${entry?.metadata?.type}`);
                },
              };
            },
          },
        ],
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "entry:./src/pages/index.tsx",
      "metadata:pages-app",
      "bundler.build",
      "bundler.entries:main",
    ]);
    expect(fs.existsSync(path.join(cwd, ".evjs"))).toBe(false);
    await expect(
      fs.promises.readFile(
        path.join(cwd, "src/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toContain('import type * as EvPage_index from "./pages/index";');
  });

  it("does not rewrite unchanged generated SPA route types", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    const routeTypesPath = path.join(cwd, "src/evjs-route-types.d.ts");

    await build(
      {
        server: false,
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );
    const firstStat = await fs.promises.stat(routeTypesPath, {
      bigint: true,
    });

    await new Promise((resolve) => setTimeout(resolve, 20));
    await build(
      {
        server: false,
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    const secondStat = await fs.promises.stat(routeTypesPath, {
      bigint: true,
    });
    expect(secondStat.mtimeNs).toBe(firstStat.mtimeNs);
  });

  it("removes stale default route types when SPA routing uses a custom directory", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src"), { recursive: true });
    await fs.promises.mkdir(path.join(cwd, "app/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    await build(
      {
        server: false,
        routing: {
          mode: "spa",
          dir: "./app/pages",
        },
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    expect(fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))).toBe(
      false,
    );
    await expect(
      fs.promises.readFile(
        path.join(cwd, "app/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toContain('import type * as EvPage_index from "./pages/index";');
  });

  it("removes stale custom route types when SPA routing returns to the default directory", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.mkdir(path.join(cwd, "app/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/pages/index.tsx"),
      "export default function AppHome() { return null; }",
      "utf-8",
    );

    await build(
      {
        server: false,
        routing: {
          mode: "spa",
          dir: "./app/pages",
        },
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );
    expect(fs.existsSync(path.join(cwd, "app/evjs-route-types.d.ts"))).toBe(
      true,
    );

    await build(
      {
        server: false,
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    expect(fs.existsSync(path.join(cwd, "app/evjs-route-types.d.ts"))).toBe(
      false,
    );
    await expect(
      fs.promises.readFile(
        path.join(cwd, "src/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toContain('import type * as EvPage_index from "./pages/index";');
  });

  it("does not remove user-authored files that share the route types file name", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.mkdir(path.join(cwd, "types"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "types/evjs-route-types.d.ts"),
      "declare const userAuthoredRouteTypes: string;",
      "utf-8",
    );

    await build(
      {
        server: false,
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    await expect(
      fs.promises.readFile(
        path.join(cwd, "types/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toBe("declare const userAuthoredRouteTypes: string;");
  });

  it("removes generated route types when routing is disabled", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.mkdir(path.join(cwd, "app"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    await build(
      {
        server: false,
        routing: false,
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    expect(fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))).toBe(
      false,
    );
    expect(fs.existsSync(path.join(cwd, "app/evjs-route-types.d.ts"))).toBe(
      false,
    );
  });

  it("removes generated route types when explicit pages config replaces routing", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.mkdir(path.join(cwd, "app"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/home.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    await build(
      {
        server: false,
        pages: {
          home: "./src/pages/home.tsx",
        },
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    expect(fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))).toBe(
      false,
    );
    expect(fs.existsSync(path.join(cwd, "app/evjs-route-types.d.ts"))).toBe(
      false,
    );
  });

  it("generates TypeScript-visible SPA route types for app navigation helpers", async () => {
    const cwd = await createWorkspaceProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages/posts"), {
      recursive: true,
    });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/posts/$postId.tsx"),
      "export default function Post() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/search.tsx"),
      [
        "export function validateSearch(search: Record<string, unknown>) {",
        "  return { q: String(search.q ?? ''), page: Number(search.page ?? 1) };",
        "}",
        "export default function Search() { return null; }",
      ].join("\n"),
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/check-links.tsx"),
      [
        'import { Link, useLinkProps } from "@evjs/client";',
        "",
        "export function CheckLinks() {",
        '  <Link to="/posts/$postId" params={{ postId: "p1" }} />;',
        '  useLinkProps({ to: "/search", search: { q: "router", page: 1 } });',
        "",
        "  // @ts-expect-error unknown page route paths are rejected.",
        '  useLinkProps({ to: "/missing" });',
        "",
        "  // @ts-expect-error dynamic page routes require their params.",
        '  useLinkProps({ to: "/posts/$postId" });',
        "",
        "  // @ts-expect-error dynamic params must match the page route segment name.",
        '  useLinkProps({ to: "/posts/$postId", params: { id: "p1" } });',
        "",
        "  // @ts-expect-error search objects follow validateSearch output.",
        '  useLinkProps({ to: "/search", search: { q: "router", page: "one" } });',
        "",
        "  return null;",
        "}",
      ].join("\n"),
      "utf-8",
    );
    await writeRouteTypeCheckTsConfig(cwd);

    await build(
      {
        server: false,
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    await execa("npx", ["tsc", "-p", path.join(cwd, "tsconfig.json")], {
      cwd: repoRoot,
    });
  });

  it("generates TypeScript-visible SPA route types for a custom route directory under src", async () => {
    const cwd = await createWorkspaceProject();
    await fs.promises.mkdir(path.join(cwd, "src/app/pages/admin"), {
      recursive: true,
    });
    await fs.promises.writeFile(
      path.join(cwd, "src/app/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/app/pages/admin/$section.tsx"),
      "export default function AdminSection() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/check-custom-dir-links.tsx"),
      [
        'import { useLinkProps } from "@evjs/client";',
        "",
        "export function CheckCustomDirLinks() {",
        '  useLinkProps({ to: "/admin/$section", params: { section: "users" } });',
        "",
        "  // @ts-expect-error unknown page route paths are rejected.",
        '  useLinkProps({ to: "/missing" });',
        "",
        "  // @ts-expect-error dynamic page routes require their params.",
        '  useLinkProps({ to: "/admin/$section" });',
        "",
        "  return null;",
        "}",
      ].join("\n"),
      "utf-8",
    );
    await writeRouteTypeCheckTsConfig(cwd);

    await build(
      {
        server: false,
        routing: {
          mode: "spa",
          dir: "./src/app/pages",
        },
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    await expect(
      fs.promises.readFile(
        path.join(cwd, "src/app/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toContain(
      'import type * as EvPage_admin_section from "./pages/admin/$section";',
    );
    await execa("npx", ["tsc", "-p", path.join(cwd, "tsconfig.json")], {
      cwd: repoRoot,
    });
  });

  it("prefers discovered page routes over the default app entry", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/main.tsx"),
      "console.log('old app entry');",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await build(
      {
        server: false,
        plugins: [
          {
            name: "records-pages-entry",
            setup() {
              return {
                buildPlan(plan) {
                  events.push(`entry:${plan.entries[0]?.import}`);
                  events.push(`metadata:${plan.entries[0]?.metadata?.type}`);
                },
              };
            },
          },
        ],
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "entry:./src/pages/index.tsx",
      "metadata:pages-app",
      "bundler.build",
      "bundler.entries:main",
    ]);
  });

  it("builds MPA pages without a router or generated route files", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.mkdir(path.join(cwd, "src/layout"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/layout/index.tsx"),
      "export function Layout() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/about.tsx"),
      "export default function About() { return null; }",
      "utf-8",
    );
    const events: string[] = [];
    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "mock-mpa",
      async build({ plan }) {
        events.push(
          `entries:${plan.entries.map((entry) => `${entry.name}:${entry.kind}`).join(",")}`,
        );
        events.push(
          `metadata:${plan.entries.map((entry) => entry.metadata?.type ?? "none").join(",")}`,
        );
        return {
          clientEntryAssets: {
            index: { js: ["index.js"], css: [] },
            about: { js: ["about.js"], css: [] },
          },
          firstClientEntryAssets: { js: ["index.js"], css: [] },
        };
      },
      async dev() {},
    };

    await build(
      {
        server: false,
        routing: {
          mode: "mpa",
        },
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "entries:index:page-client,about:page-client",
      "metadata:react-component-page,react-component-page",
    ]);
    expect(fs.existsSync(path.join(cwd, ".evjs"))).toBe(false);
    expect(fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))).toBe(
      false,
    );
  });

  it("removes stale default route types when MPA routing uses a custom directory", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src"), { recursive: true });
    await fs.promises.mkdir(path.join(cwd, "app/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    await build(
      {
        server: false,
        routing: {
          mode: "mpa",
          dir: "./app/pages",
        },
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    expect(fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))).toBe(
      false,
    );
    expect(fs.existsSync(path.join(cwd, "app/evjs-route-types.d.ts"))).toBe(
      false,
    );
  });

  it("does not remove user-authored route type declarations in MPA mode", async () => {
    const cwd = await createProject();
    const userAuthoredSource = "declare const userAuthoredRouteTypes: string;";
    await fs.promises.mkdir(path.join(cwd, "app/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "app/evjs-route-types.d.ts"),
      userAuthoredSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "app/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    await build(
      {
        server: false,
        routing: {
          mode: "mpa",
          dir: "./app/pages",
        },
      },
      {
        cwd,
        bundler: createMockBundler([]),
      },
    );

    await expect(
      fs.promises.readFile(
        path.join(cwd, "app/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toBe(userAuthoredSource);
  });

  it("passes linked BuildOutput to buildEnd and emits the framework manifest", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "memory-output",
      async build() {
        return {
          clientEntryAssets: {
            main: { js: ["memory.js"], css: [] },
          },
          firstClientEntryAssets: { js: ["memory.js"], css: [] },
        };
      },
      async dev() {},
    };

    await build(
      {
        server: false,
        plugins: [
          {
            name: "reads-memory-output",
            setup() {
              return {
                buildEnd(result) {
                  events.push(result.output.apps.default.assets.js[0] ?? "");
                },
              };
            },
          },
        ],
      },
      { cwd, bundler },
    );

    expect(events).toEqual(["memory.js"]);
    expect(fs.existsSync(path.join(cwd, "dist/manifest.json"))).toBe(true);
  });

  it("emits a public-safe manifest and keeps internal build output server-side", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/Dashboard.tsx"),
      [
        'export const render = "ssr";',
        "export default function Dashboard() { return null; }",
      ].join("\n"),
      "utf-8",
    );

    const rawOutputComponents: Array<string | undefined> = [];
    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "memory-output",
      async build() {
        return {
          clientEntryAssets: {
            dashboard: { js: ["dashboard.js"], css: [] },
          },
          firstClientEntryAssets: { js: ["dashboard.js"], css: [] },
          serverEntryAssets: {
            server: { js: ["server.js"], css: [] },
            "dashboard-server": { js: ["dashboard-server.js"], css: [] },
          },
          serverEntry: "server.js",
          serverAssets: { js: ["server.js"], css: [] },
        };
      },
      async dev() {},
    };

    await build(
      {
        pages: {
          dashboard: {
            component: "./src/pages/Dashboard.tsx",
            html: "./index.html",
          },
        },
        plugins: [
          {
            name: "records-raw-output",
            setup() {
              return {
                buildEnd(result) {
                  rawOutputComponents.push(
                    result.output.pages.dashboard.component,
                  );
                },
              };
            },
          },
        ],
      },
      { cwd, bundler },
    );

    const publicManifest = fs.readFileSync(
      path.join(cwd, "dist/manifest.json"),
      "utf-8",
    );
    const internalOutput = fs.readFileSync(
      path.join(cwd, "dist/server/build-output.json"),
      "utf-8",
    );

    expect(rawOutputComponents).toEqual(["./src/pages/Dashboard.tsx"]);
    expect(publicManifest).not.toContain(".tsx");
    expect(publicManifest).not.toContain("server.js");
    expect(internalOutput).toContain("./src/pages/Dashboard.tsx");
    expect(internalOutput).toContain("server.js");
  });

  it("runs plugin config hooks before resolving config", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    const plugin: Plugin<Record<string, never>> = {
      name: "sets-server-base-path",
      config(config, ctx) {
        events.push(`config:${ctx.mode}`);
        config.server = {
          ...(typeof config.server === "object" ? config.server : {}),
          basePath: "/api",
        };
        return config;
      },
      setup(ctx) {
        events.push(`setup:${ctx.config.server.functionRuntime.endpoint}`);
      },
    };

    await build(
      { plugins: [plugin] },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "config:production",
      "setup:/api/fn",
      "bundler.build",
      "bundler.entries:main,server",
      "bundler.endpoint:/api/fn",
    ]);
  });

  it("fails on page route convention errors before running the bundler", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages/users"), {
      recursive: true,
    });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/users/[id].tsx"),
      "export default function UserByBracketParam() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);
    let error: unknown;

    try {
      await build(
        {
          server: false,
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      );
    } catch (caught) {
      error = caught;
    }

    expect(error).toBeInstanceOf(Error);
    expect((error as Error).message).toContain(
      "[evjs] Page route discovery failed.",
    );
    expect((error as Error).message).toContain("src/pages/users/[id].tsx");
    expect((error as Error).message).toContain(
      'Dynamic page route segments must use $param filenames. Bracket segment "[id]" is not supported.',
    );
    expect(events).not.toContain("bundler.build");
  });

  it("fails on unsupported page render metadata before running the bundler", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/campaign.tsx"),
      [
        'export const render = "ppr";',
        "export const prerender = { partial: true } as const;",
        "export default function Campaign() { return null; }",
      ].join("\n"),
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      ),
    ).rejects.toThrow(
      'Page render mode "ppr" is not supported. PPR is declared with render = "ssr" and prerender = { partial: true }.',
    );
    expect(events).not.toContain("bundler.build");
  });

  it("fails when a page route has no default export", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export const title = 'Home';",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      ),
    ).rejects.toThrow(
      "Page route modules must default-export a React component. Move non-route helpers under an underscore-prefixed file or folder.",
    );
    expect(events).not.toContain("bundler.build");
  });

  it("fails when a page route cannot be parsed", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home( {",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      ),
    ).rejects.toThrow("Page route module could not be parsed:");
    expect(events).not.toContain("bundler.build");
  });

  it("fails when the root layout is placed in the page route directory", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/layout.tsx"),
      "export default function Layout() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      ),
    ).rejects.toThrow(
      "Layout files must live at ./src/layout/index.tsx. Files or folders named layout inside the page route directory are not route pages.",
    );
    expect(events).not.toContain("bundler.build");
  });

  it("fails when a nested layout is placed in the page route directory", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages/posts"), {
      recursive: true,
    });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/posts/layout.tsx"),
      "export default function PostsLayout() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      ),
    ).rejects.toThrow(
      "Layout files must live at ./src/layout/index.tsx. Files or folders named layout inside the page route directory are not route pages.",
    );
    expect(events).not.toContain("bundler.build");
  });

  it("fails when the root layout uses a file alias", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/layout.tsx"),
      "export default function Layout() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          routing: true,
        },
        {
          cwd,
          bundler,
        },
      ),
    ).rejects.toThrow(
      "Root layout must live at ./src/layout/index.tsx. ./src/layout.tsx is not supported.",
    );
    expect(events).not.toContain("bundler.build");
  });

  it("orders plugin config and lifecycle hooks by dependencies", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    const pluginA: Plugin<Record<string, never>> = {
      name: "plugin-a",
      config(config) {
        events.push("config:a");
        return config;
      },
      setup() {
        events.push("setup:a");
        return {
          buildStart() {
            events.push("buildStart:a");
          },
          buildEnd() {
            events.push("buildEnd:a");
          },
        };
      },
    };
    const pluginB: Plugin<Record<string, never>> = {
      name: "plugin-b",
      dependencies: ["plugin-a"],
      config(config) {
        events.push("config:b");
        return config;
      },
      setup() {
        events.push("setup:b");
        return {
          buildStart() {
            events.push("buildStart:b");
          },
          buildEnd() {
            events.push("buildEnd:b");
          },
        };
      },
    };

    await build(
      { server: false, plugins: [pluginB, pluginA] },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "config:a",
      "config:b",
      "setup:a",
      "setup:b",
      "buildStart:a",
      "buildStart:b",
      "bundler.build",
      "bundler.entries:main",
      "buildEnd:a",
      "buildEnd:b",
    ]);
  });

  it("preserves user order for plugins unrelated to a dependency", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    function plugin(
      name: string,
      dependencies?: string[],
    ): Plugin<Record<string, never>> {
      return {
        name,
        dependencies,
        setup() {
          events.push(`setup:${name}`);
        },
      };
    }

    await build(
      {
        server: false,
        plugins: [
          plugin("plugin-a", ["plugin-c"]),
          plugin("plugin-b"),
          plugin("plugin-c"),
        ],
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "setup:plugin-b",
      "setup:plugin-c",
      "setup:plugin-a",
      "bundler.build",
      "bundler.entries:main",
    ]);
  });

  it("orders unrelated plugins by enforce tier", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await build(
      {
        server: false,
        plugins: [
          {
            name: "post",
            enforce: "post",
            setup() {
              events.push("setup:post");
            },
          },
          {
            name: "normal",
            setup() {
              events.push("setup:normal");
            },
          },
          {
            name: "pre",
            enforce: "pre",
            setup() {
              events.push("setup:pre");
            },
          },
        ],
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "setup:pre",
      "setup:normal",
      "setup:post",
      "bundler.build",
      "bundler.entries:main",
    ]);
  });

  it("orders plugins by optional dependencies when they are present", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    function plugin(
      name: string,
      options: Pick<
        Plugin<Record<string, never>>,
        "dependencies" | "optionalDependencies"
      > = {},
    ): Plugin<Record<string, never>> {
      return {
        name,
        ...options,
        setup() {
          events.push(`setup:${name}`);
        },
      };
    }

    await build(
      {
        server: false,
        plugins: [
          plugin("plugin-b", {
            dependencies: ["plugin-c"],
            optionalDependencies: ["plugin-a"],
          }),
          plugin("plugin-c"),
          plugin("plugin-a"),
        ],
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "setup:plugin-c",
      "setup:plugin-a",
      "setup:plugin-b",
      "bundler.build",
      "bundler.entries:main",
    ]);
  });

  it("ignores optional dependencies when they are missing", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await build(
      {
        server: false,
        plugins: [
          {
            name: "plugin-b",
            dependencies: ["plugin-c"],
            optionalDependencies: ["plugin-a"],
            setup() {
              events.push("setup:plugin-b");
            },
          },
          {
            name: "plugin-c",
            setup() {
              events.push("setup:plugin-c");
            },
          },
        ],
      },
      {
        cwd,
        bundler,
      },
    );

    expect(events).toEqual([
      "setup:plugin-c",
      "setup:plugin-b",
      "bundler.build",
      "bundler.entries:main",
    ]);
  });

  it("throws when a plugin dependency is missing", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          plugins: [{ name: "plugin-b", dependencies: ["plugin-a"] }],
        },
        { cwd, bundler },
      ),
    ).rejects.toThrow('Plugin "plugin-b" depends on missing plugin "plugin-a"');
  });

  it("throws on circular plugin dependencies", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          plugins: [
            { name: "plugin-a", dependencies: ["plugin-b"] },
            { name: "plugin-b", dependencies: ["plugin-a"] },
          ],
        },
        { cwd, bundler },
      ),
    ).rejects.toThrow(
      "Circular plugin dependency detected: plugin-a -> plugin-b -> plugin-a",
    );
  });

  it("throws when optional dependencies create a cycle", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          plugins: [
            { name: "plugin-a", optionalDependencies: ["plugin-b"] },
            { name: "plugin-b", dependencies: ["plugin-a"] },
          ],
        },
        { cwd, bundler },
      ),
    ).rejects.toThrow(
      "Circular plugin dependency detected: plugin-a -> plugin-b -> plugin-a",
    );
  });

  it("throws on duplicate plugin names", async () => {
    const cwd = await createProject();
    const events: string[] = [];
    const bundler = createMockBundler(events);

    await expect(
      build(
        {
          server: false,
          plugins: [{ name: "plugin-a" }, { name: "plugin-a" }],
        },
        { cwd, bundler },
      ),
    ).rejects.toThrow('Duplicate plugin name "plugin-a"');
  });
});

describe("dev", () => {
  it("writes generated SPA route types before starting the dev bundler", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "mock",
      async build() {
        return {};
      },
      async dev({ plan }) {
        events.push(`entry:${plan.entries[0]?.import}`);
        events.push(
          `routeTypes:${fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))}`,
        );
        process.emit("SIGINT");
      },
    };

    await Promise.race([
      dev({ server: false }, { cwd, bundler }),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev startup timed out")), 2000),
      ),
    ]);

    expect(events).toEqual(["entry:./src/pages/index.tsx", "routeTypes:true"]);
    await expect(
      fs.promises.readFile(
        path.join(cwd, "src/evjs-route-types.d.ts"),
        "utf-8",
      ),
    ).resolves.toContain('import type * as EvPage_index from "./pages/index";');
  });

  it("removes stale generated route types before starting MPA dev", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/evjs-route-types.d.ts"),
      generatedRouteTypesSource,
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "mock",
      async build() {
        return {};
      },
      async dev({ plan }) {
        events.push(`entry:${plan.entries[0]?.kind}`);
        events.push(
          `routeTypes:${fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))}`,
        );
        process.emit("SIGINT");
      },
    };

    await Promise.race([
      dev(
        {
          server: false,
          routing: {
            mode: "mpa",
          },
        },
        { cwd, bundler },
      ),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev startup timed out")), 2000),
      ),
    ]);

    expect(events).toEqual(["entry:page-client", "routeTypes:false"]);
    expect(fs.existsSync(path.join(cwd, "src/evjs-route-types.d.ts"))).toBe(
      false,
    );
  });

  it("updates generated SPA route types when a nested page route is added during dev", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages/posts"), {
      recursive: true,
    });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/posts/index.tsx"),
      "export default function Posts() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createRouteUpdateBundler(cwd, events, "/posts/$postId");

    const running = dev({ server: false }, { cwd, bundler });

    await new Promise((resolve) => setTimeout(resolve, 100));
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/posts/$postId.tsx"),
      "export default function Post() { return null; }",
      "utf-8",
    );

    await Promise.race([
      running,
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev route update timed out")), 2000),
      ),
    ]);

    expect(events).toEqual([
      "initial:/,/posts",
      "changed:/,/posts,/posts/$postId",
      "types:true",
    ]);
  });

  it("updates generated SPA route types when a new nested route directory is populated during dev", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createRouteUpdateBundler(cwd, events, "/admin");

    const running = dev({ server: false }, { cwd, bundler });

    await new Promise((resolve) => setTimeout(resolve, 100));
    await fs.promises.mkdir(path.join(cwd, "src/pages/admin"), {
      recursive: true,
    });
    await new Promise((resolve) => setTimeout(resolve, 150));
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/admin/index.tsx"),
      "export default function Admin() { return null; }",
      "utf-8",
    );

    await Promise.race([
      running,
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev route update timed out")), 2000),
      ),
    ]);

    expect(events).toEqual(["initial:/", "changed:/,/admin", "types:true"]);
  });

  it("updates generated SPA route types when a page route is deleted during dev", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages/posts"), {
      recursive: true,
    });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/index.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/posts/index.tsx"),
      "export default function Posts() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/posts/$postId.tsx"),
      "export default function Post() { return null; }",
      "utf-8",
    );

    const events: string[] = [];
    const bundler = createRouteUpdateBundler(cwd, events, "/posts/$postId");

    const running = dev({ server: false }, { cwd, bundler });

    await new Promise((resolve) => setTimeout(resolve, 100));
    await fs.promises.rm(path.join(cwd, "src/pages/posts/$postId.tsx"));

    await Promise.race([
      running,
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev route update timed out")), 2000),
      ),
    ]);

    expect(events).toEqual([
      "initial:/,/posts,/posts/$postId",
      "changed:/,/posts",
      "types:false",
    ]);
  });

  it("runs dev plan update hooks when config changes add an MPA page", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/Home.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/Orders.tsx"),
      "export default function Orders() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "ev.config.ts"),
      "export default {};",
      "utf-8",
    );

    const events: string[] = [];
    const plugin: Plugin<Record<string, never>> = {
      name: "dev-plan-recorder",
      setup() {
        return {
          devPlanUpdate(update) {
            events.push(
              `hook:${update.entries.added.map((entry) => entry.name).join(",")}`,
            );
          },
        };
      },
    };
    let currentConfig: Config<Record<string, never>> = {
      server: false,
      pages: {
        home: "./src/pages/Home.tsx",
      },
      plugins: [plugin],
    };

    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "mock",
      async build() {
        return {};
      },
      async dev() {
        events.push("bundler.dev");
        return {
          async updatePlan(update) {
            events.push(
              `update:${update.entries.added.map((entry) => entry.name).join(",")}`,
            );
            process.emit("SIGINT");
          },
        };
      },
    };

    const running = dev(currentConfig, {
      cwd,
      bundler,
      loadConfig() {
        return currentConfig;
      },
    });

    await new Promise((resolve) => setTimeout(resolve, 100));
    currentConfig = {
      ...currentConfig,
      pages: {
        ...currentConfig.pages,
        orders: "./src/pages/Orders.tsx",
      },
    };
    await fs.promises.writeFile(
      path.join(cwd, "ev.config.ts"),
      "export default { pages: { home: './src/pages/Home.tsx', orders: './src/pages/Orders.tsx' } };",
      "utf-8",
    );

    await Promise.race([
      running,
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev update timed out")), 2000),
      ),
    ]);

    expect(events).toEqual(["bundler.dev", "hook:orders", "update:orders"]);
  });

  it("recreates same-name plugin hooks when dev config changes", async () => {
    const cwd = await createProject();
    await fs.promises.mkdir(path.join(cwd, "src/pages"), { recursive: true });
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/Home.tsx"),
      "export default function Home() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "src/pages/Orders.tsx"),
      "export default function Orders() { return null; }",
      "utf-8",
    );
    await fs.promises.writeFile(
      path.join(cwd, "ev.config.ts"),
      "export default {};",
      "utf-8",
    );

    const events: string[] = [];
    function createPlugin(label: string): Plugin<Record<string, never>> {
      return {
        name: "same-name-plugin",
        setup() {
          return {
            devPlanUpdate(update) {
              events.push(
                `hook:${label}:${update.entries.added.map((entry) => entry.name).join(",")}`,
              );
            },
          };
        },
      };
    }

    let currentConfig: Config<Record<string, never>> = {
      server: false,
      pages: {
        home: "./src/pages/Home.tsx",
      },
      plugins: [createPlugin("v1")],
    };

    const bundler: BundlerAdapter<Record<string, never>> = {
      name: "mock",
      async build() {
        return {};
      },
      async dev() {
        events.push("bundler.dev");
        return {
          async updatePlan(update) {
            events.push(
              `update:${update.entries.added.map((entry) => entry.name).join(",")}`,
            );
            process.emit("SIGINT");
          },
        };
      },
    };

    const running = dev(currentConfig, {
      cwd,
      bundler,
      loadConfig() {
        return currentConfig;
      },
    });

    await new Promise((resolve) => setTimeout(resolve, 100));
    currentConfig = {
      ...currentConfig,
      pages: {
        ...currentConfig.pages,
        orders: "./src/pages/Orders.tsx",
      },
      plugins: [createPlugin("v2")],
    };
    await fs.promises.writeFile(
      path.join(cwd, "ev.config.ts"),
      "export default { pages: { home: './src/pages/Home.tsx', orders: './src/pages/Orders.tsx' } };",
      "utf-8",
    );

    await Promise.race([
      running,
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("dev update timed out")), 2000),
      ),
    ]);

    expect(events).toEqual(["bundler.dev", "hook:v2:orders", "update:orders"]);
  });
});
