/**
 * Server function → TanStack Query options utility.
 *
 * Converts a server function into `{ queryKey, queryFn }` that works with
 * ANY TanStack Query hook: useQuery, useSuspenseQuery, usePrefetchQuery,
 * useInfiniteQuery, queryClient.ensureQueryData, etc.
 *
 * @example
 * import { fn } from "@evjs/runtime/client";
 * import { useQuery, useSuspenseQuery } from "@evjs/runtime/client";
 *
 * useQuery(serverFn(getUsers));
 * useSuspenseQuery(serverFn(getUser, userId));
 * useInfiniteQuery({ ...serverFn(getPosts), getNextPageParam: ... });
 * context.queryClient.ensureQueryData(serverFn(getUsers));
 */

import { __fn_call, getFnId } from "./transport";

/**
 * A server function stub as generated by the build-tools loader.
 */
export type ServerFunction<TArgs extends unknown[], TResponse> = (
  ...args: TArgs
) => Promise<TResponse>;

// biome-ignore lint/suspicious/noExplicitAny: must accept any function shape
type AnyFunction = (...args: any[]) => any;

/** Derive a stable key from a server function's build-time fnId. */
export function getBaseKey(fn: AnyFunction): string {
  return getFnId(fn) || fn.name || "unknown";
}

/**
 * Convert a server function + args into TanStack Query options.
 *
 * Returns `{ queryKey, queryFn }` compatible with any TanStack Query hook.
 *
 * @example
 * useQuery(serverFn(getUsers));
 * useSuspenseQuery(serverFn(getUser, userId));
 * context.queryClient.ensureQueryData(serverFn(getUsers));
 */
export function serverFn<TArgs extends unknown[], TData>(
  serverFn: (...args: TArgs) => Promise<TData>,
  ...args: TArgs
): {
  queryKey: unknown[];
  queryFn: (ctx: { signal: AbortSignal }) => Promise<TData>;
} {
  const baseKey = getBaseKey(serverFn as AnyFunction);
  const fnId = getFnId(serverFn as AnyFunction);
  return {
    queryKey: [baseKey, ...args],
    queryFn: fnId
      ? ({ signal }) => __fn_call(fnId, args, { signal }) as Promise<TData>
      : () => serverFn(...args),
  };
}
