import {
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
  type UseSuspenseQueryOptions,
  type UseSuspenseQueryResult,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";

/**
 * A server function stub as generated by the evjs webpack loader.
 */
// biome-ignore lint/suspicious/noExplicitAny: generic boundary
export type ServerFunction<TArgs extends any[], TResponse> = ((
  ...args: TArgs
) => Promise<TResponse>) & {
  _evId?: string;
};

// ── Proxy Types ──────────────────────────────────────────

/**
 * The interface for a single server function's query proxy.
 */
// biome-ignore lint/suspicious/noExplicitAny: generic boundary
export interface QueryProxyHandler<TArgs extends any[], TResponse> {
  /** Call the server function directly. */
  (...args: TArgs): Promise<TResponse>;

  /** Use as a standard TanStack Query. */
  useQuery(
    args: TArgs,
    options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">,
  ): UseQueryResult<TResponse, Error>;

  /** Use as a TanStack Suspense Query. */
  useSuspenseQuery(
    args: TArgs,
    options?: Omit<
      UseSuspenseQueryOptions<TResponse, Error>,
      "queryKey" | "queryFn"
    >,
  ): UseSuspenseQueryResult<TResponse, Error>;

  /** Returns standard TanStack Query options. */
  queryOptions(
    args: TArgs,
    options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">,
    // biome-ignore lint/suspicious/noExplicitAny: generic boundary
  ): UseQueryOptions<TResponse, Error> & { queryKey: any[]; queryFn: any };

  /** Returns the query key for this function and arguments. */
  // biome-ignore lint/suspicious/noExplicitAny: generic boundary
  queryKey(args?: TArgs): any[];

  /** The stable function ID (internal). */
  _evId: string;
}

/**
 * The interface for a single server function's mutation proxy.
 */
export interface MutationProxyHandler<TVariables, TResponse> {
  /** Call the server function directly. */
  (variables: TVariables): Promise<TResponse>;

  /** Use as a TanStack Mutation. */
  useMutation(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >,
  ): UseMutationResult<TResponse, Error, TVariables>;

  /** Returns standard TanStack Mutation options. */
  mutationOptions(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >,
    // biome-ignore lint/suspicious/noExplicitAny: generic boundary
  ): UseMutationOptions<TResponse, Error, TVariables> & { mutationFn: any };

  /** The stable function ID (internal). */
  _evId: string;
}

/**
 * A recursive proxy that maps property access to server function stubs.
 */
export type QueryProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TArgs,
    infer TResponse
  >
    ? QueryProxyHandler<TArgs, TResponse>
    : QueryProxy<TModule[K]>;
};

export type MutationProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TVars,
    infer TResponse
  >
    ? MutationProxyHandler<TVars, TResponse>
    : MutationProxy<TModule[K]>;
};

// ── Implementation ───────────────────────────────────────

// biome-ignore lint/suspicious/noExplicitAny: Internal helper creating dynamic proxies
function createHandler(fn: any, path: string[]) {
  return {
    // biome-ignore lint/suspicious/noExplicitAny: Dynamic proxy arguments
    useQuery: (args: any[] = [], options?: any) => {
      return useQuery({
        ...options,
        queryKey: [fn._evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      });
    },
    // biome-ignore lint/suspicious/noExplicitAny: Dynamic proxy arguments
    useSuspenseQuery: (args: any[] = [], options?: any) => {
      return useSuspenseQuery({
        ...options,
        queryKey: [fn._evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      });
    },
    // biome-ignore lint/suspicious/noExplicitAny: Dynamic proxy options
    useMutation: (options?: any) => {
      return useMutation({
        ...options,
        // biome-ignore lint/suspicious/noExplicitAny: Dynamic proxy variables
        mutationFn: (variables: any) => fn(variables),
      });
    },
    // biome-ignore lint/suspicious/noExplicitAny: Dynamic proxy arguments
    queryOptions: (args: any[] = [], options?: any) => {
      return {
        ...options,
        queryKey: [fn._evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      };
    },
    // biome-ignore lint/suspicious/noExplicitAny: Dynamic proxy options
    mutationOptions: (options?: any) => {
      return {
        ...options,
        // biome-ignore lint/suspicious/noExplicitAny: proxy args
        mutationFn: (variables: any) => fn(variables),
      };
    },
    // biome-ignore lint/suspicious/noExplicitAny: proxy args
    queryKey: (args: any[] = []) => {
      return [fn._evId || path.join("."), ...args];
    },
    _evId: fn._evId,
    path: path.join("."),
  };
}

function createProxy(
  type: "query" | "mutation",
  // biome-ignore lint/suspicious/noExplicitAny: proxy source
  source?: any,
  path: string[] = [],
  // biome-ignore lint/suspicious/noExplicitAny: proxy return
): any {
  const target = source ?? (() => {});
  return new Proxy(target, {
    get(_target, prop: string) {
      // biome-ignore lint/suspicious/noExplicitAny: target cast
      if (prop === "_evId") return (_target as any)._evId;

      const newPath = [...path, prop];
      const val = source ? source[prop] : undefined;

      // If we have a source and this is a function, return the handler
      if (typeof val === "function") {
        return createHandler(val, newPath);
      }

      // Otherwise return a nested proxy
      return createProxy(type, val, newPath);
    },
    apply(_target, _thisArg, args) {
      const fn = args[0];
      if (typeof fn === "function") {
        return createHandler(fn, path);
      }
      return fn; // Fallback
    },
  });
}

/**
 * Create a type-safe query proxy for a module or object.
 */
export function createQueryProxy<T>(source?: T): QueryProxy<T> {
  return createProxy("query", source) as QueryProxy<T>;
}

/**
 * Create a type-safe mutation proxy for a module or object.
 */
export function createMutationProxy<T>(source?: T): MutationProxy<T> {
  return createProxy("mutation", source) as MutationProxy<T>;
}

/**
 * The global query proxy/wrapper.
 * @example
 * const { data } = query(getUsers).useQuery();
 * // or with a typed proxy:
 * const api = createQueryProxy(getUsersModule);
 * const { data } = api.getUsers.useQuery();
 */
// biome-ignore lint/suspicious/noExplicitAny: proxy generic
export const query = createProxy("query") as (<TArgs extends any[], TResponse>(
  fn: ServerFunction<TArgs, TResponse>,
) => QueryProxyHandler<TArgs, TResponse>) &
  // biome-ignore lint/suspicious/noExplicitAny: proxy generic
  QueryProxy<any>;

/**
 * The global mutation proxy/wrapper.
 * @example const { mutate } = mutation(createUser).useMutation();
 */
export const mutation = createProxy("mutation") as (<TVariables, TResponse>(
  fn: (args: TVariables) => Promise<TResponse>,
) => MutationProxyHandler<TVariables, TResponse>) &
  // biome-ignore lint/suspicious/noExplicitAny: proxy generic
  MutationProxy<any>;

// ── Legacy Hooks (deprecated) ──────────────────────────

/** @deprecated Use query.fnName.useQuery() */
// biome-ignore lint/suspicious/noExplicitAny: legacy args
export function useServerQuery<TArgs extends any[], TResponse, TError = Error>(
  serverFn: ServerFunction<TArgs, TResponse>,
  args: TArgs,
  options?: Omit<UseQueryOptions<TResponse, TError>, "queryKey" | "queryFn">,
): UseQueryResult<TResponse, TError> {
  const queryKey = [serverFn._evId || serverFn.name, ...args];
  return useQuery({
    ...options,
    queryKey,
    queryFn: () => serverFn(...args),
  });
}

/** @deprecated Use mutation.fnName.useMutation() */
export function useServerMutation<TVariables, TResponse, TError = Error>(
  serverFn: (args: TVariables) => Promise<TResponse>,
  options?: Omit<
    UseMutationOptions<TResponse, TError, TVariables>,
    "mutationFn"
  >,
): UseMutationResult<TResponse, TError, TVariables> {
  return useMutation({
    ...options,
    mutationFn: (variables: TVariables) => serverFn(variables),
  });
}
