/**
 * @evjs/ev — config, plugin, and bundler types for the evjs framework.
 */

export type * from "@evjs/shared/manifest";
export {
  createPublicManifest,
  getClientRouteMatches,
  getClientRouteTarget,
  getServerRenderedPagePaths,
  getServerRenderedPaths,
  getServerRenderedRoutePaths,
  isRouteDerivedPage,
  isServerRenderedPage,
  linkBuildOutput,
  linkRemoteManifest,
  resolveRoutes,
} from "@evjs/shared/manifest";
export type {
  BundlerAdapter,
  BundlerBuildContext,
  BundlerBuildFacts,
  BundlerDevContext,
  BundlerDevController,
} from "./bundler.js";
export { type BuildOptions, build, type DevOptions, dev } from "./commands.js";
export {
  type AppConfig,
  type BuildResult,
  type BundlerCtx,
  CONFIG_DEFAULTS,
  type Config,
  type DevConfig,
  type DevProxyRule,
  defineConfig,
  type FileRoutesConfig,
  type HtmlDocument,
  type HtmlDocumentInfo,
  type HtmlTransformContext,
  isMpa,
  type PageConfig,
  type PageObjectConfig,
  type Plugin,
  type PluginConfigContext,
  type PluginContext,
  type PluginHooks,
  type RemoteBuildConfig,
  type RemoteBuildEntryConfig,
  type RemoteConfig,
  type ResolvedAppConfig,
  type ResolvedConfig,
  type ResolvedDevConfig,
  type ResolvedFileRoutesConfig,
  type ResolvedFunctionRuntimeConfig,
  type ResolvedRemoteBuildConfig,
  type ResolvedRemoteBuildEntryConfig,
  type ResolvedRemoteConfig,
  type ResolvedServerConfig,
  type ResolvedServerDevConfig,
  type ResolvedServerRscConfig,
  type ResolvedTransportConfig,
  resolveConfig,
  type ServerConfig,
  type ServerDevConfig,
  type ServerRscConfig,
  type TransportConfig,
} from "./config.js";
export {
  createDeploymentArtifact,
  createEdgeDeploymentFiles,
  createNodeDeploymentFiles,
  createStaticDeploymentFiles,
  type DeploymentApp,
  type DeploymentArtifact,
  type DeploymentArtifactOptions,
  type DeploymentPage,
  type DeploymentRoute,
  type DeploymentRsc,
  type DeploymentServer,
  type EdgeDeploymentAdapterOptions,
  type EdgeDeploymentFiles,
  edgeDeploymentAdapter,
  type NodeDeploymentAdapterOptions,
  type NodeDeploymentFiles,
  nodeDeploymentAdapter,
  type StaticDeploymentAdapterOptions,
  type StaticDeploymentFiles,
  staticDeploymentAdapter,
} from "./deployment.js";
export { type BuildHtmlOptions, buildHtml } from "./html.js";
export { type ConfigPatch, merge } from "./merge.js";
