/**
 * Client-side runtime utilities.
 */

export { ServerFunctionError } from "@evjs/shared";
export type { App, CreateAppOptions, CreateAppRouterOptions } from "./app.js";
export { createApp } from "./app.js";
export type { AppRouteContext } from "./context.js";
export { createAppRootRoute } from "./context.js";
export {
  getFnQueryKey,
  getFnQueryOptions,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "./query.js";
export type {
  ActiveLinkOptions,
  AnyRootRoute,
  AnyRoute,
  AnyRouteMatch,
  AnyRouter,
  AwaitOptions,
  BlockerFn,
  ErrorComponentProps,
  ErrorRouteComponent,
  HistoryLocation,
  HistoryState,
  LinkOptions,
  LinkProps,
  LocationRewrite,
  LocationRewriteFunction,
  MatchRouteOptions,
  NavigateOptions,
  NotFoundError,
  NotFoundRouteComponent,
  NotFoundRouteProps,
  ParsedLocation,
  ParsedPath,
  QueryKey,
  RegisteredRouter,
  RouteComponent,
  RouteMask,
  RouteMatch,
  RouteOptions,
  RouterConstructorOptions,
  RouterEvent,
  RouterEvents,
  RouterHistory,
  RouterListener,
  RouterOptions,
  RouterProps,
  RouterState,
  SearchFilter,
  SearchMiddleware,
  SearchParser,
  SearchSchemaInput,
  SearchSerializer,
  ShouldBlockFn,
  ToMaskOptions,
  ToOptions,
  UseBlockerOpts,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseLinkPropsOptions,
  UseMatchRouteOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "./tanstack.js";
export {
  Await,
  Block,
  CatchBoundary,
  CatchNotFound,
  ClientOnly,
  composeRewrites,
  createBrowserHistory,
  createHashHistory,
  createLink,
  createMemoryHistory,
  createRootRoute,
  createRootRouteWithContext,
  createRoute,
  createRouteMask,
  createRouter,
  DefaultGlobalNotFound,
  defaultParseSearch,
  defaultStringifySearch,
  defer,
  ErrorComponent,
  getRouteApi,
  isNotFound,
  isRedirect,
  keepPreviousData,
  Link,
  lazyRouteComponent,
  linkOptions,
  Match,
  Matches,
  MatchRoute,
  Navigate,
  notFound,
  Outlet,
  parseSearchWith,
  QueryClient,
  QueryClientProvider,
  RouteApi,
  RouterContextProvider,
  RouterProvider,
  redirect,
  retainSearchParams,
  rootRouteWithContext,
  ScrollRestoration,
  stringifySearchWith,
  stripSearchParams,
  useAwaited,
  useBlocker,
  useCanGoBack,
  useChildMatches,
  useElementScrollRestoration,
  useHydrated,
  useInfiniteQuery,
  useIsFetching,
  useLinkProps,
  useLoaderData,
  useLoaderDeps,
  useLocation,
  useMatch,
  useMatches,
  useMatchRoute,
  useNavigate,
  useParams,
  useParentMatches,
  usePrefetchQuery,
  useQueryClient,
  useRouteContext,
  useRouter,
  useRouterState,
  useSearch,
} from "./tanstack.js";
// biome-ignore lint/suspicious/noEmptyInterface: Users augment this interface with their app router type.
export interface Register {}

type ClientRegister = Register;

// Bridge evjs' public Register interface into TanStack Router's global types.
declare module "@tanstack/react-router" {
  interface Register extends ClientRegister {}
}

export type { PageRuntimeOptions } from "./page.js";
export { startPageRuntime } from "./page.js";
export type {
  ReactPageMountOptions,
  ReactPageRuntimeOptions,
  RemoteReactModuleExports,
  RemoteReactProps,
  RemoteRuntimeContext,
  RemoteRuntimeSharedContext,
  RscDebugPayload,
  RscDebugPayloadMountOptions,
  RscFlightFetchOptions,
  RscPayload,
  RscPayloadMountOptions,
} from "./react.js";
export {
  createReactPageModule,
  createRemoteReactModule,
  createRemoteRuntimeContext,
  fetchRscDebugPayload,
  fetchRscFlight,
  fetchRscPayload,
  loadRscDebugPage,
  loadRscPage,
  mountReactPage,
  mountRscDebugPayload,
  mountRscPayload,
  useRemoteContext,
} from "./react.js";
export type {
  RemoteAppHookOptions,
  RemoteAppHookResult,
  RemoteAppProps,
  RemoteAppRuntimeController,
  RemoteAppRuntimeOptions,
  RemoteAppShellOptions,
  RemoteAppState,
  RemoteAppStatus,
  RemoteAppTargetOptions,
} from "./remote-app.js";
export {
  createRemoteAppManifest,
  formatRemoteSharedNegotiation,
  getRemoteSharedVersion,
  RemoteApp,
  resolveRemoteAppManifestUrl,
  startRemoteAppRuntime,
  useRemoteHost,
} from "./remote-app.js";
export type {
  PageReference,
  ReactAppDeclaration,
  ReactAppOptions,
  ReactRouteDeclaration,
  ReactRouteOptions,
  ReactRoutes,
} from "./routes.js";
export { defineReactApp, defineReactRoutes, page, route } from "./routes.js";
export type {
  ReactRscModelOptions,
  ReactRscMountOptions,
  ReactRscRuntimeBootstrap,
} from "./rsc.js";
export {
  createReactRscModel,
  mountReactRscPage,
  startReactRscPageRuntime,
  unmountReactRscPage,
} from "./rsc.js";
export type {
  ActivationRequest,
  AppContext,
  AppModule,
  HistoryDriver,
  HistoryDriverOptions,
  PageDriver,
  PageDriverOptions,
  RemoteManifestLoadContext,
  RemoteSharedDependenciesWarning,
  RemoteSharedNegotiationContext,
  RemoteSharedResolution,
  SharedScope,
  SharedScopeEntry,
  Shell,
  ShellDriver,
  ShellErrorContext,
  ShellModuleRegistration,
  ShellOptions,
  ShellWarningContext,
} from "./shell.js";
export {
  createActivationRequestFromUrl,
  createHistoryDriver,
  createPageDriver,
  createShell,
  loadSharedDependency,
  registerSharedDependency,
  registerShellModule,
} from "./shell.js";
export type {
  HeaderFactory,
  RequestContext,
  ServerFunction,
  TransportAdapter,
  TransportOptions,
} from "./transport.js";
export {
  callServer,
  createServerReference,
  getFnId,
  getFnName,
  initTransport,
  initTransportFromManifest,
} from "./transport.js";
