import fs from "node:fs/promises";
import path from "node:path";
import {
  analyzePageComponentExports,
  type PageComponentExportKind,
  validateHtmlTemplate,
} from "@evjs/ev/_internal/build";

const DEFAULT_PAGES_DIR = "src/pages";
const SMALLFISH_CONFIG_FILES = [
  "smallfish.config.ts",
  "smallfish.config.cts",
  "smallfish.config.js",
  "smallfish.config.cjs",
] as const;
const PAGE_SOURCE_EXTENSIONS = [".tsx", ".ts", ".jsx", ".js"] as const;
const PAGE_CONFIG_FILES = ["page.config.ts", "page.config.js"] as const;
const PAGE_FACET_BASENAMES = ["layout", "error", "not-found"] as const;
const SMALLFISH_GLOBAL_SOURCE_FILES = PAGE_SOURCE_EXTENSIONS.map(
  (extension) => `global${extension}`,
);
const SMALLFISH_GLOBAL_STYLE_EXTENSIONS = new Set([".css", ".less"]);
const SMALLFISH_CONFIG_OVERRIDE_ENV = "SMALLFISH_CUSTOM_CONFIG";
const SMALLFISH_MIGRATION_MARKER = "Generated by ev migrate smallfish.";
const SUPPORTED_PAGE_CONFIG_FIELDS = new Set([
  "title",
  "head",
  "router",
  "htmlFileExtension",
]);
const STATIC_HTML_EXTENSIONS = new Set([".html", ".htm"]);
const UNSAFE_METADATA_KEYS = new Set(["__proto__", "constructor", "prototype"]);
const STATIC_ROUTE_SEGMENT_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._~-]*$/;

export type SmallfishMigrationDiagnosticLevel = "error" | "warning";

export type SmallfishMigrationDiagnosticCode =
  | "AMBIGUOUS_ROOT_PAGE"
  | "CUSTOM_PAGES_DIRECTORY"
  | "DUPLICATE_CANONICAL_CONFIG"
  | "DUPLICATE_ENTRY"
  | "DOCUMENT_OUTPUT_CONFLICT"
  | "EXPLICIT_PAGES"
  | "INVALID_METADATA"
  | "INVALID_PAGE_CONFIG"
  | "INVALID_PAGE_DIRECTORY"
  | "INVALID_PAGE_ENTRY"
  | "INVALID_HTML_TEMPLATE"
  | "MISSING_ENTRY"
  | "MISSING_HTML_TEMPLATE"
  | "MISSING_PAGES_DIRECTORY"
  | "PAGE_CONFIG_CONFLICT"
  | "PAGES_DIRECTORY_OUTSIDE_PROJECT"
  | "SYMLINK_PAGE_DIRECTORY"
  | "UNEXPECTED_CORE_CONVENTION"
  | "UNSUPPORTED_GLOBAL_SOURCE"
  | "UNSUPPORTED_HEAD"
  | "UNSUPPORTED_PAGE_CONFIG"
  | "UNSUPPORTED_PAGE_OVERRIDE"
  | "UNSUPPORTED_PROJECT_CONFIG"
  | "UNSUPPORTED_SOURCE_FILE"
  | "UNSUPPORTED_ROUTER";

export interface SmallfishMigrationDiagnostic {
  level: SmallfishMigrationDiagnosticLevel;
  code: SmallfishMigrationDiagnosticCode;
  message: string;
  file?: string;
}

export type SmallfishMigrationChange =
  | {
      kind: "write";
      file: string;
      content: string;
    }
  | {
      kind: "delete";
      file: string;
    };

export interface SmallfishDocumentAlias {
  pageDirectory: string;
  canonicalFileName: string;
  legacyFileName: string;
}

export interface SmallfishMigrationOptions {
  cwd?: string;
  /**
   * Smallfish's resolved baseDir/appBaseDir/pagesDir location, relative to cwd.
   *
   * The migration deliberately does not execute smallfish.config.*. Pass this
   * when the project does not use the default src/pages location.
   */
  pagesDir?: string;
  /** Apply the preflighted changes. The default is a read-only dry run. */
  write?: boolean;
}

export interface SmallfishMigrationResult {
  cwd: string;
  pagesDir: string;
  /** Value to use for evjs `routing.dir`. */
  routingDir: string;
  diagnostics: SmallfishMigrationDiagnostic[];
  changes: SmallfishMigrationChange[];
  documentAliases: SmallfishDocumentAlias[];
  applied: boolean;
}

interface PageMetadataMigration {
  title?: string;
  meta?: Record<string, string>;
}

interface PageConfigMigration {
  metadata?: PageMetadataMigration;
  legacyOutput: string;
}

interface PlannedPageMigration {
  changes: SmallfishMigrationChange[];
  diagnostics: SmallfishMigrationDiagnostic[];
  alias?: SmallfishDocumentAlias;
  document?: PlannedDocumentOutput;
}

interface PlannedDocumentOutput {
  pageDirectory: string;
  canonicalFileName: string;
  aliases: string[];
}

interface ProjectConfigToken {
  kind: "identifier" | "number" | "punctuation" | "string";
  value: string;
  escaped?: boolean;
}

type ProjectConfigAnalysis =
  | {
      properties: Set<string>;
    }
  | {
      error: string;
    };

/**
 * Preflight and optionally apply a one-time Smallfish Page source migration.
 *
 * This rewrites stored application source only. It does not enable a
 * compatibility runtime or teach evjs to read Smallfish conventions.
 */
export async function migrateSmallfishProject(
  options: SmallfishMigrationOptions = {},
): Promise<SmallfishMigrationResult> {
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const pagesDirInput = options.pagesDir ?? DEFAULT_PAGES_DIR;
  const pagesDir = path.resolve(cwd, pagesDirInput);
  const displayPagesDir = toProjectPath(cwd, pagesDir);
  const routingDir = toRoutingDir(cwd, pagesDir);
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  const changes: SmallfishMigrationChange[] = [];
  const documentAliases: SmallfishDocumentAlias[] = [];
  const documentOutputs: PlannedDocumentOutput[] = [];

  if (!isPathInside(cwd, pagesDir)) {
    diagnostics.push({
      level: "error",
      code: "PAGES_DIRECTORY_OUTSIDE_PROJECT",
      file: normalizePath(pagesDirInput),
      message:
        "The Smallfish pages directory must resolve inside the project root.",
    });
    return createResult({
      cwd,
      pagesDir: displayPagesDir,
      routingDir,
      diagnostics,
      changes,
      documentAliases,
      applied: false,
    });
  }

  diagnostics.push(
    ...(await inspectSmallfishProjectConfig(
      cwd,
      options.pagesDir !== undefined,
    )),
  );

  const pagesStat = await statIfExists(pagesDir);
  if (!pagesStat?.isDirectory()) {
    diagnostics.push({
      level: "error",
      code: "MISSING_PAGES_DIRECTORY",
      file: displayPagesDir,
      message: `Smallfish pages directory "${displayPagesDir}" does not exist or is not a directory.`,
    });
    return createResult({
      cwd,
      pagesDir: displayPagesDir,
      routingDir,
      diagnostics,
      changes,
      documentAliases,
      applied: false,
    });
  }

  diagnostics.push(...(await inspectSharedHtmlTemplate(cwd)));
  diagnostics.push(
    ...(await inspectImplicitSmallfishAppEntries(cwd, pagesDir)),
  );
  diagnostics.push(...(await inspectActivatedCoreConventions(cwd, pagesDir)));

  const entries = await fs.readdir(pagesDir, { withFileTypes: true });
  const rootCandidates = await inspectRegularFileCandidates(cwd, pagesDir, [
    ...PAGE_SOURCE_EXTENSIONS.map((extension) => `page${extension}`),
    ...PAGE_CONFIG_FILES,
  ]);
  diagnostics.push(...rootCandidates.diagnostics);
  const rootPageEntries = PAGE_SOURCE_EXTENSIONS.flatMap((extension) => {
    const name = `page${extension}`;
    return rootCandidates.files.has(name) ? [name] : [];
  });
  if (rootPageEntries.length > 1) {
    diagnostics.push({
      level: "error",
      code: "DUPLICATE_ENTRY",
      file: displayPagesDir,
      message: `Pages root has multiple canonical page.* entry variants: ${rootPageEntries.join(
        ", ",
      )}. Keep exactly one.`,
    });
  } else if (rootPageEntries.length === 1) {
    documentOutputs.push({
      pageDirectory: displayPagesDir,
      canonicalFileName: "index.html",
      aliases: [],
    });
  }
  for (const entry of entries.sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    if (entry.isSymbolicLink()) continue;
    if (!entry.isDirectory()) continue;
    const migration = await inspectPageDirectory(cwd, pagesDir, entry.name);
    diagnostics.push(...migration.diagnostics);
    changes.push(...migration.changes);
    if (migration.alias) documentAliases.push(migration.alias);
    if (migration.document) documentOutputs.push(migration.document);
  }
  diagnostics.push(...findDocumentOutputConflicts(documentOutputs));

  sortDiagnostics(diagnostics);
  const hasErrors = diagnostics.some(
    (diagnostic) => diagnostic.level === "error",
  );
  let applied = false;
  if (options.write && !hasErrors && changes.length > 0) {
    await applyMigrationChanges(cwd, changes);
    applied = true;
  }

  return createResult({
    cwd,
    pagesDir: displayPagesDir,
    routingDir,
    diagnostics,
    changes,
    documentAliases,
    applied,
  });
}

async function inspectImplicitSmallfishAppEntries(
  cwd: string,
  pagesDir: string,
): Promise<SmallfishMigrationDiagnostic[]> {
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  const appSourceDir = path.dirname(pagesDir);
  const globalSources = await inspectRegularFileCandidates(
    cwd,
    appSourceDir,
    SMALLFISH_GLOBAL_SOURCE_FILES,
  );
  diagnostics.push(...globalSources.diagnostics);

  const discoveredGlobalSources = SMALLFISH_GLOBAL_SOURCE_FILES.filter((file) =>
    globalSources.files.has(file),
  ).map((file) => toProjectPath(cwd, path.join(appSourceDir, file)));
  if (discoveredGlobalSources.length > 0) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_GLOBAL_SOURCE",
      file: discoveredGlobalSources.join(", "),
      message:
        "Smallfish automatically imports global.* into every Page entry, but Core 0.3 treats it as private source. Move its side effects behind explicit imports from the canonical Page tree before rerunning migration.",
    });
  }

  const stylesDir = path.join(appSourceDir, "styles");
  const styleSources = await collectImplicitSmallfishStyleSources(
    cwd,
    stylesDir,
    diagnostics,
  );
  if (styleSources.length > 0) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_GLOBAL_SOURCE",
      file: styleSources.join(", "),
      message:
        "Smallfish automatically injects styles/**/*.{css,less} into every Page, but Core 0.3 requires explicit style imports. Import these styles from the canonical Application or Page source and move them out of the auto-injected directory before rerunning migration.",
    });
  }

  return diagnostics;
}

async function collectImplicitSmallfishStyleSources(
  cwd: string,
  directory: string,
  diagnostics: SmallfishMigrationDiagnostic[],
): Promise<string[]> {
  const stat = await statIfExists(directory);
  if (!stat) return [];
  if (stat.isSymbolicLink()) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_SOURCE_FILE",
      file: toProjectPath(cwd, directory),
      message:
        "The Smallfish global styles directory is a symlink and cannot be statically verified. Replace it with direct source before migration.",
    });
    return [];
  }
  if (!stat.isDirectory()) return [];

  const sources: string[] = [];
  const entries = await fs.readdir(directory, { withFileTypes: true });
  for (const entry of entries.sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    const file = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) {
      diagnostics.push({
        level: "error",
        code: "UNSUPPORTED_SOURCE_FILE",
        file: toProjectPath(cwd, file),
        message:
          "A Smallfish global style candidate is a symlink and cannot be statically verified. Replace it with direct source before migration.",
      });
      continue;
    }
    if (entry.isDirectory()) {
      sources.push(
        ...(await collectImplicitSmallfishStyleSources(cwd, file, diagnostics)),
      );
      continue;
    }
    if (
      entry.isFile() &&
      SMALLFISH_GLOBAL_STYLE_EXTENSIONS.has(path.extname(entry.name))
    ) {
      sources.push(toProjectPath(cwd, file));
    }
  }
  return sources;
}

async function inspectSmallfishProjectConfig(
  cwd: string,
  hasExplicitPagesDir: boolean,
): Promise<SmallfishMigrationDiagnostic[]> {
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  const customConfig = process.env[SMALLFISH_CONFIG_OVERRIDE_ENV];
  if (customConfig?.trim()) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_PROJECT_CONFIG",
      file: SMALLFISH_CONFIG_OVERRIDE_ENV,
      message: `${SMALLFISH_CONFIG_OVERRIDE_ENV} is set to ${JSON.stringify(
        customConfig,
      )}. An environment-selected Smallfish config can change the final Page inventory and cannot be statically verified; unset it and pass the resolved Page root with --pages-dir only after auditing the original resolved config.`,
    });
  }
  const candidates: Array<{ file: string; source: string }> = [];
  for (const fileName of SMALLFISH_CONFIG_FILES) {
    const file = path.join(cwd, fileName);
    const stat = await statIfExists(file);
    if (stat?.isSymbolicLink()) {
      diagnostics.push({
        level: "error",
        code: "UNSUPPORTED_PROJECT_CONFIG",
        file: toProjectPath(cwd, file),
        message:
          "Symlinked Smallfish project config cannot be statically verified. Replace it with a direct config file before migration.",
      });
      continue;
    }
    if (stat && !stat.isFile()) {
      diagnostics.push({
        level: "error",
        code: "UNSUPPORTED_PROJECT_CONFIG",
        file: toProjectPath(cwd, file),
        message:
          "Smallfish project config candidates must be direct regular files. Directories and special files cannot be statically verified.",
      });
      continue;
    }
    if (!stat) continue;
    candidates.push({
      file: toProjectPath(cwd, file),
      source: await fs.readFile(file, "utf-8"),
    });
  }
  if (candidates.length > 1) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_PROJECT_CONFIG",
      file: candidates.map((candidate) => candidate.file).join(", "),
      message:
        "Multiple Smallfish project config files were found, so the migration cannot statically prove which one owns Page discovery. Keep one config file before migration.",
    });
    return diagnostics;
  }
  const selected = candidates[0];
  if (!selected) return diagnostics;

  const analysis = analyzeSmallfishProjectConfig(selected.source);
  if ("error" in analysis) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_PROJECT_CONFIG",
      file: selected.file,
      message: `Smallfish project config cannot be statically verified: ${analysis.error} The migration never executes or imports project config; rewrite it as a direct object literal before migration.`,
    });
    return diagnostics;
  }

  if (analysis.properties.has("pages")) {
    diagnostics.push({
      level: "error",
      code: "EXPLICIT_PAGES",
      file: selected.file,
      message:
        "Explicit Smallfish pages cannot be migrated by directory scanning because page names, roots, entries, and outputs may diverge. Remove the explicit mapping after migrating those Pages manually.",
    });
  }

  const structuralFields = ["baseDir", "appBaseDir", "pagesDir"].filter(
    (field) => analysis.properties.has(field),
  );
  if (structuralFields.length > 0 && !hasExplicitPagesDir) {
    diagnostics.push({
      level: "error",
      code: "CUSTOM_PAGES_DIRECTORY",
      file: selected.file,
      message: `Smallfish config declares ${structuralFields.join(
        " and ",
      )}. The migration does not execute Smallfish config; pass the resolved location with --pages-dir.`,
    });
  }

  const executableConfigFields = ["plugins", "presets"].filter((field) =>
    analysis.properties.has(field),
  );
  if (executableConfigFields.length > 0) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_PROJECT_CONFIG",
      file: selected.file,
      message: `Smallfish config declares ${executableConfigFields.join(
        " and ",
      )}. Plugins and presets can modify the final Page inventory, so directory scanning cannot prove this migration safe. Inspect the original resolved config and migrate those extensions manually before rerunning.`,
    });
  }

  const documentAndStyleFields = [
    "layout",
    "layoutsDir",
    "mountElementId",
    "globalStylesDir",
  ].filter((field) => analysis.properties.has(field));
  if (documentAndStyleFields.length > 0) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_PROJECT_CONFIG",
      file: selected.file,
      message: `Smallfish config declares ${documentAndStyleFields.join(
        " and ",
      )}. Layout templates, mount ownership, and automatic global style entries do not have a mechanical Core migration. Freeze the final shared HTML shell and mount in index.html, convert global styles to explicit imports, and remove these Smallfish fields before rerunning.`,
    });
  }

  return diagnostics;
}

async function inspectPageDirectory(
  cwd: string,
  pagesDir: string,
  pageDirectoryName: string,
): Promise<PlannedPageMigration> {
  const directory = path.join(pagesDir, pageDirectoryName);
  const displayDirectory = toProjectPath(cwd, directory);
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  const changes: SmallfishMigrationChange[] = [];
  const isRootPage = pageDirectoryName === "index";

  if (!STATIC_ROUTE_SEGMENT_PATTERN.test(pageDirectoryName)) {
    diagnostics.push({
      level: "error",
      code: "INVALID_PAGE_DIRECTORY",
      file: displayDirectory,
      message: `Smallfish Page directory "${pageDirectoryName}" is not a canonical static evjs route segment. Rename or reorganize it before migration.`,
    });
  }

  const inspectedCandidates = await inspectRegularFileCandidates(
    cwd,
    directory,
    [
      ...PAGE_SOURCE_EXTENSIONS.flatMap((extension) => [
        `index${extension}`,
        `page${extension}`,
      ]),
      ...PAGE_CONFIG_FILES,
      "config.json",
    ],
  );
  diagnostics.push(...inspectedCandidates.diagnostics);
  const regularFiles = inspectedCandidates.files;
  const legacyEntries = PAGE_SOURCE_EXTENSIONS.flatMap((extension) => {
    const name = `index${extension}`;
    return regularFiles.has(name) ? [name] : [];
  });
  const canonicalEntries = PAGE_SOURCE_EXTENSIONS.flatMap((extension) => {
    const name = `page${extension}`;
    return regularFiles.has(name) ? [name] : [];
  });
  const rootEntries = isRootPage
    ? await collectRegularFiles(
        pagesDir,
        PAGE_SOURCE_EXTENSIONS.map((extension) => `page${extension}`),
      )
    : [];
  const generatedAnchorFile = isRootPage
    ? rootEntries[0]
      ? path.join(pagesDir, rootEntries[0])
      : undefined
    : canonicalEntries[0]
      ? path.join(directory, canonicalEntries[0])
      : undefined;
  const hasGeneratedPageAnchor = generatedAnchorFile
    ? await fileContainsMigrationMarker(generatedAnchorFile)
    : false;
  const hasGeneratedRootAnchor =
    isRootPage && rootEntries.length === 1 && hasGeneratedPageAnchor;
  const legacyEntryExportKind =
    legacyEntries.length === 1
      ? await inspectLegacyPageEntry(
          cwd,
          path.join(directory, legacyEntries[0] as string),
          diagnostics,
        )
      : undefined;

  if (legacyEntries.length > 1) {
    diagnostics.push({
      level: "error",
      code: "DUPLICATE_ENTRY",
      file: displayDirectory,
      message: `Smallfish Page has multiple index.* entry variants: ${legacyEntries.join(
        ", ",
      )}. Keep exactly one before migration.`,
    });
  }
  if (canonicalEntries.length > 1) {
    diagnostics.push({
      level: "error",
      code: "DUPLICATE_ENTRY",
      file: displayDirectory,
      message: `Page has multiple canonical page.* entry variants: ${canonicalEntries.join(
        ", ",
      )}. Keep exactly one.`,
    });
  }
  if (
    legacyEntries.length > 0 &&
    canonicalEntries.length > 0 &&
    !hasGeneratedPageAnchor
  ) {
    diagnostics.push({
      level: "error",
      code: "DUPLICATE_ENTRY",
      file: displayDirectory,
      message: `Both Smallfish entry "${legacyEntries[0]}" and canonical entry "${canonicalEntries[0]}" exist. Resolve the duplicate before migration.`,
    });
  }
  if (
    isRootPage &&
    legacyEntries.length > 0 &&
    rootEntries.length > 0 &&
    !hasGeneratedRootAnchor
  ) {
    diagnostics.push({
      level: "error",
      code: "DUPLICATE_ENTRY",
      file: toProjectPath(cwd, pagesDir),
      message: `Smallfish root Page "${legacyEntries[0]}" cannot create its canonical root anchor because ${rootEntries.join(
        ", ",
      )} already exists in the pages root.`,
    });
  }
  if (isRootPage && legacyEntries.length === 0 && canonicalEntries.length > 0) {
    diagnostics.push({
      level: "error",
      code: "AMBIGUOUS_ROOT_PAGE",
      file: displayDirectory,
      message:
        "A canonical src/pages/index/page.* anchor maps to /index, while Smallfish's src/pages/index/index.* mapped to /. The migration cannot infer whether this was a partial root migration; restore the Smallfish entry or create an explicit root src/pages/page.* anchor manually.",
    });
  }
  if (legacyEntries.length === 0 && canonicalEntries.length === 0) {
    diagnostics.push({
      level: "warning",
      code: "MISSING_ENTRY",
      file: displayDirectory,
      message:
        "Directory has neither an index.* Smallfish entry nor a page.* evjs anchor and was left unchanged.",
    });
  }

  const needsEntryMigration =
    legacyEntries.length === 1 &&
    canonicalEntries.length === 0 &&
    !hasGeneratedRootAnchor;
  if (needsEntryMigration) {
    const legacyEntry = legacyEntries[0];
    if (legacyEntry && legacyEntryExportKind) {
      const extension = path.extname(legacyEntry);
      if (isRootPage) {
        changes.push({
          kind: "write",
          file: toProjectPath(cwd, path.join(pagesDir, `page${extension}`)),
          content: createPageAnchorSource(
            "./index/index",
            legacyEntryExportKind,
          ),
        });
      } else {
        changes.push({
          kind: "write",
          file: toProjectPath(cwd, path.join(directory, `page${extension}`)),
          content: createPageAnchorSource("./index", legacyEntryExportKind),
        });
      }
    }
  }

  const colocatedCanonicalConfigs = PAGE_CONFIG_FILES.filter((file) =>
    regularFiles.has(file),
  );
  const targetDirectory = isRootPage ? pagesDir : directory;
  const rootCanonicalConfigs = isRootPage
    ? await collectRegularFiles(pagesDir, PAGE_CONFIG_FILES)
    : [];
  const canonicalConfigs = isRootPage
    ? [...colocatedCanonicalConfigs, ...rootCanonicalConfigs]
    : colocatedCanonicalConfigs;
  if (colocatedCanonicalConfigs.length > 1 || rootCanonicalConfigs.length > 1) {
    diagnostics.push({
      level: "error",
      code: "DUPLICATE_CANONICAL_CONFIG",
      file: toProjectPath(cwd, targetDirectory),
      message: `Page has both ${canonicalConfigs.join(
        " and ",
      )}. Keep exactly one canonical Page config module.`,
    });
  }

  const legacyConfigName = "config.json";
  const hasLegacyConfig = regularFiles.has(legacyConfigName);
  let configMigration: PageConfigMigration | undefined = {
    legacyOutput: `${pageDirectoryName}.html`,
  };
  if (hasLegacyConfig) {
    const legacyConfigFile = path.join(directory, legacyConfigName);
    const displayLegacyConfig = toProjectPath(cwd, legacyConfigFile);
    const inspected = await inspectPageConfig(
      legacyConfigFile,
      displayLegacyConfig,
      pageDirectoryName,
    );
    diagnostics.push(...inspected.diagnostics);
    configMigration = inspected.config;
  }

  const canonicalOutput = isRootPage
    ? "index.html"
    : `${normalizePath(pageDirectoryName)}/index.html`;
  const aliases =
    !configMigration || configMigration.legacyOutput === canonicalOutput
      ? []
      : [configMigration.legacyOutput];
  const hasPartiallyMigratedNonRootPage =
    !isRootPage && legacyEntries.length === 0 && canonicalEntries.length === 1;
  const shouldEnsurePageConfig =
    needsEntryMigration ||
    hasPartiallyMigratedNonRootPage ||
    (hasGeneratedPageAnchor && hasLegacyConfig);
  const generatedConfigAlreadyPreservesAliases =
    !hasLegacyConfig &&
    canonicalConfigs.length === 1 &&
    (await fileContainsMigrationMarker(
      isRootPage
        ? path.join(pagesDir, canonicalConfigs[0] as string)
        : path.join(directory, canonicalConfigs[0] as string),
    ));
  const canWritePageConfig =
    shouldEnsurePageConfig &&
    canonicalConfigs.length === 0 &&
    !hasErrorDiagnostics(diagnostics);

  if (
    shouldEnsurePageConfig &&
    canonicalConfigs.length > 0 &&
    !generatedConfigAlreadyPreservesAliases
  ) {
    diagnostics.push({
      level: "error",
      code: "PAGE_CONFIG_CONFLICT",
      file: toProjectPath(cwd, targetDirectory),
      message: `Cannot add migrated metadata and static output aliases because ${canonicalConfigs.join(
        " and ",
      )} already exists. Merge document.aliases manually before rerunning migration.`,
    });
  }

  if (canWritePageConfig) {
    const metadata = configMigration?.metadata;
    if (metadata || aliases.length > 0) {
      changes.push({
        kind: "write",
        file: toProjectPath(cwd, path.join(targetDirectory, "page.config.ts")),
        content: createPageConfigSource(metadata, aliases),
      });
    }
  }

  if (regularFiles.has(legacyConfigName)) {
    const legacyConfigFile = path.join(directory, legacyConfigName);
    const displayLegacyConfig = toProjectPath(cwd, legacyConfigFile);
    if (canWritePageConfig) {
      changes.push({
        kind: "delete",
        file: displayLegacyConfig,
      });
    }
  }

  return {
    changes,
    diagnostics,
    ...((needsEntryMigration ||
      hasPartiallyMigratedNonRootPage ||
      canonicalEntries.length === 1) &&
    (!isRootPage ||
      (rootEntries.length === 0 &&
        (needsEntryMigration || canonicalEntries.length === 1)))
      ? {
          document: {
            pageDirectory: displayDirectory,
            canonicalFileName:
              needsEntryMigration && isRootPage
                ? "index.html"
                : `${normalizePath(pageDirectoryName)}/index.html`,
            aliases:
              needsEntryMigration || hasPartiallyMigratedNonRootPage
                ? aliases
                : [],
          },
        }
      : {}),
    ...((needsEntryMigration || hasPartiallyMigratedNonRootPage) &&
    aliases.length === 1 &&
    STATIC_ROUTE_SEGMENT_PATTERN.test(pageDirectoryName)
      ? {
          alias: {
            pageDirectory: displayDirectory,
            canonicalFileName: canonicalOutput,
            legacyFileName: aliases[0] as string,
          },
        }
      : {}),
  };
}

async function inspectPageConfig(
  absoluteFile: string,
  displayFile: string,
  pageName: string,
): Promise<{
  parsed: boolean;
  config?: PageConfigMigration;
  diagnostics: SmallfishMigrationDiagnostic[];
}> {
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  let value: unknown;
  try {
    value = JSON.parse(await fs.readFile(absoluteFile, "utf-8"));
  } catch (error) {
    diagnostics.push({
      level: "error",
      code: "INVALID_PAGE_CONFIG",
      file: displayFile,
      message: `Smallfish Page config is not valid JSON: ${getErrorMessage(error)}`,
    });
    return { parsed: false, diagnostics };
  }
  if (!isPlainObject(value)) {
    diagnostics.push({
      level: "error",
      code: "INVALID_PAGE_CONFIG",
      file: displayFile,
      message: "Smallfish Page config must contain a JSON object.",
    });
    return { parsed: false, diagnostics };
  }

  const unsupportedFields = Object.keys(value).filter(
    (field) => !SUPPORTED_PAGE_CONFIG_FIELDS.has(field),
  );
  for (const field of unsupportedFields) {
    diagnostics.push(createUnsupportedPageConfigDiagnostic(field, displayFile));
  }

  const metadata: PageMetadataMigration = {};
  if (Object.hasOwn(value, "title")) {
    if (typeof value.title !== "string") {
      diagnostics.push({
        level: "error",
        code: "INVALID_METADATA",
        file: displayFile,
        message: 'Smallfish Page config field "title" must be a string.',
      });
    } else {
      metadata.title = value.title;
    }
  }

  if (Object.hasOwn(value, "head")) {
    const resolvedHead = resolveNamedMeta(value.head, displayFile);
    diagnostics.push(...resolvedHead.diagnostics);
    if (resolvedHead.meta && Object.keys(resolvedHead.meta).length > 0) {
      metadata.meta = resolvedHead.meta;
    }
  }

  const legacyOutput = resolveLegacyPageOutput(
    value,
    pageName,
    displayFile,
    diagnostics,
  );
  return {
    parsed: true,
    ...(legacyOutput
      ? {
          config: {
            ...(Object.keys(metadata).length > 0 ? { metadata } : {}),
            legacyOutput,
          },
        }
      : {}),
    diagnostics,
  };
}

function resolveLegacyPageOutput(
  value: Record<string, unknown>,
  pageName: string,
  file: string,
  diagnostics: SmallfishMigrationDiagnostic[],
): string | undefined {
  const router = value.router ?? "";
  const extension = value.htmlFileExtension ?? ".html";
  if (typeof router !== "string") {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_ROUTER",
      file,
      message: 'Smallfish Page config field "router" must be a string.',
    });
    return undefined;
  }
  if (typeof extension !== "string" || !STATIC_HTML_EXTENSIONS.has(extension)) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_PAGE_CONFIG",
      file,
      message:
        'Smallfish Page config field "htmlFileExtension" must be exactly ".html" or ".htm" so a Document alias cannot overwrite JavaScript, CSS, metadata, or another non-HTML artifact.',
    });
    return undefined;
  }
  if (/[:*$[\]]/.test(router)) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_ROUTER",
      file,
      message: `Smallfish dynamic router "${router}" cannot identify one static Document alias. Move the route to canonical evjs SPA routing manually.`,
    });
    return undefined;
  }
  if (
    router &&
    (router.startsWith("/") ||
      router.includes(".") ||
      !/[A-Za-z0-9]$/.test(router))
  ) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_ROUTER",
      file,
      message: `Smallfish router "${router}" is not a safe static output route. It must be relative, contain no ".", and end with a letter or number.`,
    });
    return undefined;
  }
  const output = normalizePath(`${router || pageName}${extension}`);
  const outputError = getStaticOutputPathError(output);
  if (outputError) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_ROUTER",
      file,
      message: `Smallfish router/htmlFileExtension resolves to unsafe static output "${output}": ${outputError}`,
    });
    return undefined;
  }
  return output;
}

function resolveNamedMeta(
  value: unknown,
  file: string,
): {
  meta?: Record<string, string>;
  diagnostics: SmallfishMigrationDiagnostic[];
} {
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  if (!Array.isArray(value)) {
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_HEAD",
      file,
      message:
        'Smallfish Page config field "head" must be an array to migrate named metadata.',
    });
    return { diagnostics };
  }

  const meta = Object.create(null) as Record<string, string>;
  const namesByAsciiLowerCase = new Map<string, string>();
  for (const [index, entry] of value.entries()) {
    if (
      !Array.isArray(entry) ||
      entry.length < 2 ||
      entry.length > 3 ||
      entry[0] !== "meta" ||
      !isPlainObject(entry[1]) ||
      (entry.length === 3 && entry[2] !== undefined && entry[2] !== "")
    ) {
      diagnostics.push({
        level: "error",
        code: "UNSUPPORTED_HEAD",
        file,
        message: `Smallfish head[${index}] is not a plain <meta name="..." content="..."> entry and cannot be represented by evjs page.config.ts metadata.`,
      });
      continue;
    }
    const attributes = entry[1];
    const attributeKeys = Object.keys(attributes).sort();
    if (
      attributeKeys.length !== 2 ||
      attributeKeys[0] !== "content" ||
      attributeKeys[1] !== "name" ||
      typeof attributes.name !== "string" ||
      typeof attributes.content !== "string"
    ) {
      diagnostics.push({
        level: "error",
        code: "UNSUPPORTED_HEAD",
        file,
        message: `Smallfish head[${index}] must contain only string "name" and "content" attributes to migrate into evjs metadata.`,
      });
      continue;
    }
    const name = attributes.name;
    if (name.length === 0) {
      diagnostics.push({
        level: "error",
        code: "INVALID_METADATA",
        file,
        message: `Smallfish head[${index}] metadata name must be non-empty.`,
      });
      continue;
    }
    if (name.trim() !== name) {
      diagnostics.push({
        level: "error",
        code: "INVALID_METADATA",
        file,
        message: `Smallfish head[${index}] metadata name "${name}" must not include leading or trailing whitespace.`,
      });
      continue;
    }
    if (UNSAFE_METADATA_KEYS.has(name)) {
      diagnostics.push({
        level: "error",
        code: "INVALID_METADATA",
        file,
        message: `Smallfish head[${index}] metadata name "${name}" is not a safe page.config.ts metadata key.`,
      });
      continue;
    }
    const normalizedName = asciiLowerCase(name);
    const conflictingName = namesByAsciiLowerCase.get(normalizedName);
    if (conflictingName !== undefined) {
      diagnostics.push({
        level: "error",
        code: "INVALID_METADATA",
        file,
        message: `Smallfish head metadata names "${conflictingName}" and "${name}" conflict because HTML meta names are ASCII case-insensitive.`,
      });
      continue;
    }
    namesByAsciiLowerCase.set(normalizedName, name);
    meta[name] = attributes.content;
  }
  return {
    ...(Object.keys(meta).length > 0 ? { meta } : {}),
    diagnostics,
  };
}

function createUnsupportedPageConfigDiagnostic(
  field: string,
  file: string,
): SmallfishMigrationDiagnostic {
  if (field === "router") {
    return {
      level: "error",
      code: "UNSUPPORTED_ROUTER",
      file,
      message:
        'Smallfish Page config field "router" changes URL and output identity. Move the Page to the matching canonical route directory before rerunning migration.',
    };
  }
  if (field === "entry" || field === "root" || field === "name") {
    return {
      level: "error",
      code: "UNSUPPORTED_PAGE_OVERRIDE",
      file,
      message: `Smallfish Page config field "${field}" changes Page discovery identity and must be migrated manually.`,
    };
  }
  return {
    level: "error",
    code: "UNSUPPORTED_PAGE_CONFIG",
    file,
    message: `Smallfish Page config field "${field}" has no lossless core page.config.ts mapping. Migrate it to an evjs plugin or application code before rerunning migration.`,
  };
}

function createPageConfigSource(
  metadata: PageMetadataMigration | undefined,
  aliases: string[],
): string {
  const fields: string[] = [];
  if (metadata?.title !== undefined) {
    fields.push(`  title: ${JSON.stringify(metadata.title)},`);
  }
  if (metadata?.meta) {
    const meta = JSON.stringify(metadata.meta, null, 2)
      .split("\n")
      .map((line, index) => (index === 0 ? line : `  ${line}`))
      .join("\n");
    fields.push(`  meta: ${meta},`);
  }
  if (aliases.length > 0) {
    const aliasSource = JSON.stringify(aliases, null, 2)
      .split("\n")
      .map((line, index) => (index === 0 ? line : `    ${line}`))
      .join("\n");
    fields.push("  document: {");
    fields.push(`    aliases: ${aliasSource},`);
    fields.push("  },");
  }
  return [
    `// ${SMALLFISH_MIGRATION_MARKER}`,
    'import { definePageConfig } from "@evjs/ev";',
    "",
    "export default definePageConfig({",
    ...fields,
    "});",
    "",
  ].join("\n");
}

async function inspectLegacyPageEntry(
  cwd: string,
  file: string,
  diagnostics: SmallfishMigrationDiagnostic[],
): Promise<PageComponentExportKind | undefined> {
  const analysis = analyzePageComponentExports(
    await fs.readFile(file, "utf-8"),
  );
  if ("kind" in analysis) return analysis.kind;

  diagnostics.push({
    level: "error",
    code: "INVALID_PAGE_ENTRY",
    file: toProjectPath(cwd, file),
    message: `Smallfish Page entry cannot become a canonical Page anchor because ${analysis.error}.`,
  });
  return undefined;
}

function createPageAnchorSource(
  importPath: string,
  exportKind: PageComponentExportKind,
): string {
  if (exportKind === "named-page") {
    return [
      `// ${SMALLFISH_MIGRATION_MARKER}`,
      `export { Page as default } from ${JSON.stringify(importPath)};`,
      `export * from ${JSON.stringify(importPath)};`,
      "",
    ].join("\n");
  }
  return [
    `// ${SMALLFISH_MIGRATION_MARKER}`,
    `export { default } from ${JSON.stringify(importPath)};`,
    `export * from ${JSON.stringify(importPath)};`,
    "",
  ].join("\n");
}

async function applyMigrationChanges(
  cwd: string,
  changes: SmallfishMigrationChange[],
): Promise<void> {
  const rollbacks: Array<() => Promise<void>> = [];
  try {
    for (const change of changes) {
      if (change.kind === "write") {
        const file = resolveProjectFile(cwd, change.file);
        await fs.writeFile(file, change.content, {
          encoding: "utf-8",
          flag: "wx",
        });
        rollbacks.push(() => fs.rm(file, { force: true }));
        continue;
      }
      const file = resolveProjectFile(cwd, change.file);
      const source = await fs.readFile(file);
      await fs.unlink(file);
      rollbacks.push(() => fs.writeFile(file, source, { flag: "wx" }));
    }
  } catch (error) {
    const rollbackErrors: unknown[] = [];
    for (const rollback of rollbacks.reverse()) {
      try {
        await rollback();
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError);
      }
    }
    if (rollbackErrors.length > 0) {
      throw new AggregateError(
        [error, ...rollbackErrors],
        "Smallfish migration failed and could not fully roll back.",
        { cause: error },
      );
    }
    throw error;
  }
}

export function formatSmallfishMigrationResult(
  result: SmallfishMigrationResult,
): string {
  const lines = [
    `Smallfish Page migration (${result.applied ? "applied" : "dry run"})`,
    `Pages: ${result.pagesDir}`,
    `evjs routing.dir: ${result.routingDir}`,
  ];
  if (result.changes.length === 0) {
    lines.push("Changes: none");
  } else {
    lines.push("Changes:");
    for (const change of result.changes) {
      lines.push(`  ${change.kind} ${change.file}`);
    }
  }
  if (result.documentAliases.length > 0) {
    lines.push("Migrated static HTML aliases:");
    for (const alias of result.documentAliases) {
      lines.push(
        `  ${alias.legacyFileName} -> ${alias.canonicalFileName} (${alias.pageDirectory})`,
      );
    }
  }
  if (result.diagnostics.length > 0) {
    lines.push("Diagnostics:");
    for (const diagnostic of result.diagnostics) {
      const location = diagnostic.file ? ` ${diagnostic.file}:` : "";
      lines.push(
        `  ${diagnostic.level.toUpperCase()} [${diagnostic.code}]${location} ${diagnostic.message}`,
      );
    }
  }
  if (
    !result.applied &&
    result.changes.length > 0 &&
    !result.diagnostics.some((diagnostic) => diagnostic.level === "error")
  ) {
    lines.push("Run with --write to apply these source changes.");
  }
  return `${lines.join("\n")}\n`;
}

function createResult(
  result: SmallfishMigrationResult,
): SmallfishMigrationResult {
  return result;
}

function sortDiagnostics(diagnostics: SmallfishMigrationDiagnostic[]): void {
  diagnostics.sort(
    (left, right) =>
      (left.file ?? "").localeCompare(right.file ?? "") ||
      left.code.localeCompare(right.code) ||
      left.message.localeCompare(right.message),
  );
}

function hasErrorDiagnostics(
  diagnostics: SmallfishMigrationDiagnostic[],
): boolean {
  return diagnostics.some((diagnostic) => diagnostic.level === "error");
}

function findDocumentOutputConflicts(
  documents: PlannedDocumentOutput[],
): SmallfishMigrationDiagnostic[] {
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  const owners = new Map<
    string,
    { pageDirectory: string; kind: "canonical output" | "alias" }
  >();
  for (const document of documents) {
    const outputs = [
      {
        fileName: document.canonicalFileName,
        kind: "canonical output" as const,
      },
      ...document.aliases.map((fileName) => ({
        fileName,
        kind: "alias" as const,
      })),
    ];
    for (const output of outputs) {
      const previous = owners.get(output.fileName);
      if (previous) {
        diagnostics.push({
          level: "error",
          code: "DOCUMENT_OUTPUT_CONFLICT",
          file: document.pageDirectory,
          message: `Static Document ${output.kind} "${output.fileName}" conflicts with ${previous.kind} from "${previous.pageDirectory}". Canonical outputs and aliases must be globally unique.`,
        });
        continue;
      }
      owners.set(output.fileName, {
        pageDirectory: document.pageDirectory,
        kind: output.kind,
      });
    }
  }
  return diagnostics;
}

async function inspectSharedHtmlTemplate(
  cwd: string,
): Promise<SmallfishMigrationDiagnostic[]> {
  const file = path.join(cwd, "index.html");
  const displayFile = toProjectPath(cwd, file);
  const stat = await statIfExists(file);
  if (!stat) {
    return [
      {
        level: "error",
        code: "MISSING_HTML_TEMPLATE",
        file: displayFile,
        message:
          'Smallfish migration requires an audited shared index.html template containing the default evjs mount "#app". Freeze the final Smallfish layout into that template before writing Page anchors.',
      },
    ];
  }
  if (!stat.isFile()) {
    return [
      {
        level: "error",
        code: "INVALID_HTML_TEMPLATE",
        file: displayFile,
        message:
          "The shared index.html template must be a direct regular file. Symlinks, directories, and special files cannot be preflighted safely.",
      },
    ];
  }

  let document: ReturnType<typeof validateHtmlTemplate>;
  try {
    document = validateHtmlTemplate({
      template: file,
      displayName: displayFile,
    });
  } catch (error) {
    return [
      {
        level: "error",
        code: "INVALID_HTML_TEMPLATE",
        file: displayFile,
        message: `The shared index.html template is not a valid evjs Document template: ${getErrorMessage(
          error,
        )}`,
      },
    ];
  }
  if (!document.querySelector("#app")) {
    return [
      {
        level: "error",
        code: "INVALID_HTML_TEMPLATE",
        file: displayFile,
        message:
          'The shared index.html template does not contain the default evjs mount "#app". Unify the Smallfish mount and final static layout before writing Page anchors.',
      },
    ];
  }
  return [];
}

async function inspectRegularFileCandidates(
  cwd: string,
  directory: string,
  names: readonly string[],
): Promise<{
  files: Set<string>;
  diagnostics: SmallfishMigrationDiagnostic[];
}> {
  const files = new Set<string>();
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  for (const name of new Set(names)) {
    const file = path.join(directory, name);
    const stat = await statIfExists(file);
    if (!stat) continue;
    if (stat.isFile()) {
      files.add(name);
      continue;
    }
    diagnostics.push({
      level: "error",
      code: "UNSUPPORTED_SOURCE_FILE",
      file: toProjectPath(cwd, file),
      message: `Migration candidate "${name}" must be a direct regular file. ${
        stat.isSymbolicLink()
          ? "Symbolic links"
          : "Directories and special files"
      } cannot be preflighted safely and will not be overwritten.`,
    });
  }
  return { files, diagnostics };
}

async function inspectActivatedCoreConventions(
  cwd: string,
  pagesDir: string,
): Promise<SmallfishMigrationDiagnostic[]> {
  const diagnostics: SmallfishMigrationDiagnostic[] = [];
  const rootLegacyEntries = await collectRegularFiles(
    path.join(pagesDir, "index"),
    PAGE_SOURCE_EXTENSIONS.map((extension) => `index${extension}`),
  );

  await visit(pagesDir);
  return diagnostics;

  async function visit(directory: string): Promise<void> {
    const relativeDirectory = path.relative(pagesDir, directory);
    const segments = relativeDirectory
      ? relativeDirectory.split(path.sep).filter(Boolean)
      : [];
    const depth = segments.length;
    const directoryName = segments[segments.length - 1];
    const pageEntries = await collectRegularFiles(
      directory,
      PAGE_SOURCE_EXTENSIONS.map((extension) => `page${extension}`),
    );
    const legacyEntries = await collectRegularFiles(
      directory,
      PAGE_SOURCE_EXTENSIONS.map((extension) => `index${extension}`),
    );
    const willOwnPageDocument =
      pageEntries.length > 0 ||
      (depth === 0 && rootLegacyEntries.length > 0) ||
      (depth === 1 && directoryName !== "index" && legacyEntries.length > 0);

    if (depth >= 2) {
      for (const extension of PAGE_SOURCE_EXTENSIONS) {
        await diagnoseUnexpectedConvention(
          path.join(directory, `page${extension}`),
          "A recursive page.* file was private Smallfish source but becomes a canonical evjs Page and Route.",
        );
      }
    }
    for (const basename of PAGE_FACET_BASENAMES) {
      for (const extension of PAGE_SOURCE_EXTENSIONS) {
        await diagnoseUnexpectedConvention(
          path.join(directory, `${basename}${extension}`),
          `The ${basename}.* file becomes an evjs route facet after migration.`,
        );
      }
    }
    if (willOwnPageDocument) {
      await diagnoseUnexpectedConvention(
        path.join(directory, "index.html"),
        "The index.html file becomes the evjs Page Document template after the page.* anchor is active.",
      );
    }

    const entries = await fs.readdir(directory, { withFileTypes: true });
    for (const entry of entries.sort((left, right) =>
      left.name.localeCompare(right.name),
    )) {
      const child = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) {
        const stat = await statIfExists(child);
        if (stat?.isSymbolicLink()) {
          const target = await fs.stat(child).catch(() => undefined);
          if (target?.isDirectory()) {
            diagnostics.push({
              level: "error",
              code: "SYMLINK_PAGE_DIRECTORY",
              file: toProjectPath(cwd, child),
              message:
                "Symlinked directories under the Smallfish Pages tree cannot be recursively preflighted and are not migrated automatically.",
            });
          }
        }
        continue;
      }
      if (entry.isDirectory()) await visit(child);
    }
  }

  async function diagnoseUnexpectedConvention(
    file: string,
    activation: string,
  ): Promise<void> {
    const stat = await statIfExists(file);
    if (!stat) return;
    if (!stat.isFile()) {
      diagnostics.push({
        level: "error",
        code: "UNSUPPORTED_SOURCE_FILE",
        file: toProjectPath(cwd, file),
        message: `Core convention candidate "${path.basename(
          file,
        )}" must be a direct regular file. Symbolic links, directories, and special files cannot be preflighted safely.`,
      });
      return;
    }
    diagnostics.push({
      level: "error",
      code: "UNEXPECTED_CORE_CONVENTION",
      file: toProjectPath(cwd, file),
      message: `${activation} Confirm that behavior explicitly, then rename or migrate the file manually before rerunning this source migration.`,
    });
  }
}

async function collectRegularFiles(
  directory: string,
  names: readonly string[],
): Promise<string[]> {
  const files: string[] = [];
  for (const name of names) {
    const stat = await statIfExists(path.join(directory, name));
    if (stat?.isFile()) files.push(name);
  }
  return files;
}

async function fileContainsMigrationMarker(file: string): Promise<boolean> {
  try {
    return (await fs.readFile(file, "utf-8")).includes(
      SMALLFISH_MIGRATION_MARKER,
    );
  } catch (error) {
    if (hasNodeErrorCode(error, "ENOENT")) return false;
    throw error;
  }
}

function getStaticOutputPathError(value: string): string | undefined {
  if (value.trim() !== value) {
    return "leading or trailing whitespace is not allowed";
  }
  if (value.includes("\\")) return "backslashes are not allowed";
  if (value.startsWith("/") || /^[A-Za-z]:\//.test(value)) {
    return "the output must be relative";
  }
  if (value.includes("?") || value.includes("#")) {
    return "query strings and hashes are not allowed";
  }
  if (value.endsWith("/")) return 'the output must not end with "/"';
  if (
    value
      .split("/")
      .some((segment) => segment === "" || segment === "." || segment === "..")
  ) {
    return 'empty, ".", and ".." path segments are not allowed';
  }
  return undefined;
}

/**
 * Prove the top-level discovery fields without evaluating project code.
 *
 * The accepted subset is deliberately smaller than JavaScript: one direct
 * object export with explicit keys. Anything capable of hiding a top-level
 * field is a migration blocker.
 */
function analyzeSmallfishProjectConfig(source: string): ProjectConfigAnalysis {
  const tokenized = tokenizeProjectConfig(source);
  if ("error" in tokenized) return tokenized;

  const tokens = tokenized.tokens;
  let index = 0;
  if (
    tokens[index]?.kind === "string" &&
    tokens[index]?.value === "use strict" &&
    !tokens[index]?.escaped &&
    tokens[index + 1]?.value === ";"
  ) {
    index += 2;
  }

  if (
    tokens[index]?.value === "export" &&
    tokens[index + 1]?.value === "default"
  ) {
    index += 2;
  } else if (
    tokens[index]?.value === "module" &&
    tokens[index + 1]?.value === "." &&
    tokens[index + 2]?.value === "exports" &&
    tokens[index + 3]?.value === "="
  ) {
    index += 4;
  } else if (
    tokens[index]?.value === "exports" &&
    tokens[index + 1]?.value === "." &&
    tokens[index + 2]?.value === "default" &&
    tokens[index + 3]?.value === "="
  ) {
    index += 4;
  } else {
    return {
      error:
        "the file must contain only `export default { ... }` or a direct CommonJS object assignment; imports, declarations, and indirect exports are unsupported.",
    };
  }

  if (tokens[index]?.value !== "{") {
    return {
      error:
        "the exported value must be a direct object literal; functions, calls, identifiers, and imported indirection are unsupported.",
    };
  }
  const parsed = parseProjectConfigObject(tokens, index + 1);
  if ("error" in parsed) return parsed;

  index = parsed.nextIndex;
  while (tokens[index]?.value === ";") index += 1;
  if (index !== tokens.length) {
    return {
      error: "the direct object export must be the only statement in the file.",
    };
  }
  return { properties: parsed.properties };
}

function parseProjectConfigObject(
  tokens: ProjectConfigToken[],
  startIndex: number,
):
  | {
      properties: Set<string>;
      nextIndex: number;
    }
  | {
      error: string;
    } {
  const properties = new Set<string>();
  let index = startIndex;
  let expectsProperty = true;

  while (index < tokens.length) {
    const token = tokens[index];
    if (!token) break;
    if (token.value === "}") {
      return {
        properties,
        nextIndex: index + 1,
      };
    }
    if (!expectsProperty) {
      if (token.value !== ",") {
        return {
          error: "each top-level object property must be separated by a comma.",
        };
      }
      index += 1;
      expectsProperty = true;
      continue;
    }
    if (token.value === ",") {
      return {
        error: "empty top-level object entries are unsupported.",
      };
    }
    if (token.value === "...") {
      return {
        error:
          "top-level object spread can hide Page discovery, layout, mount, style, or plugin fields.",
      };
    }
    if (token.value === "[") {
      return {
        error:
          "computed top-level properties cannot be proven safe for Page discovery.",
      };
    }
    if (
      token.kind !== "identifier" &&
      (token.kind !== "string" || token.escaped)
    ) {
      return {
        error:
          "top-level properties must use direct identifier or unescaped string keys.",
      };
    }
    if (token.value === "__proto__") {
      return {
        error:
          'the special top-level "__proto__" property can hide inherited Page discovery fields.',
      };
    }
    const property = token.value;
    index += 1;
    if (tokens[index]?.value !== ":") {
      return {
        error:
          "top-level shorthand, methods, getters, and setters cannot be proven safe for Page discovery.",
      };
    }
    properties.add(property);
    index += 1;

    const valueStart = index;
    const expectedClosings: string[] = [];
    while (index < tokens.length) {
      const valueToken = tokens[index];
      if (!valueToken) break;
      if (
        expectedClosings.length === 0 &&
        (valueToken.value === "," || valueToken.value === "}")
      ) {
        break;
      }
      const closing = getProjectConfigClosingToken(valueToken.value);
      if (closing) {
        expectedClosings.push(closing);
      } else if (
        valueToken.value === ")" ||
        valueToken.value === "]" ||
        valueToken.value === "}"
      ) {
        if (expectedClosings.pop() !== valueToken.value) {
          return {
            error: `the value for top-level property "${property}" has unbalanced delimiters.`,
          };
        }
      }
      index += 1;
    }
    if (index === valueStart) {
      return {
        error: `top-level property "${property}" has no value.`,
      };
    }
    if (expectedClosings.length > 0) {
      return {
        error: `the value for top-level property "${property}" has unbalanced delimiters.`,
      };
    }
    expectsProperty = false;
  }

  return {
    error: "the direct project config object is not closed.",
  };
}

function tokenizeProjectConfig(source: string):
  | {
      tokens: ProjectConfigToken[];
    }
  | {
      error: string;
    } {
  const tokens: ProjectConfigToken[] = [];
  let index = 0;
  while (index < source.length) {
    const character = source[index];
    if (!character) break;
    if (/\s/.test(character)) {
      index += 1;
      continue;
    }
    if (character === "/" && source[index + 1] === "/") {
      index += 2;
      while (
        index < source.length &&
        source[index] !== "\n" &&
        source[index] !== "\r"
      ) {
        index += 1;
      }
      continue;
    }
    if (character === "/" && source[index + 1] === "*") {
      const end = source.indexOf("*/", index + 2);
      if (end === -1) {
        return {
          error: "the project config contains an unterminated comment.",
        };
      }
      index = end + 2;
      continue;
    }
    if (character === "/") {
      return {
        error:
          "regular-expression and division expressions are outside the safe static config subset.",
      };
    }
    if (character === "`") {
      return {
        error: "template literals are outside the safe static config subset.",
      };
    }
    if (character === '"' || character === "'") {
      const stringToken = readProjectConfigString(source, index, character);
      if ("error" in stringToken) return stringToken;
      tokens.push(stringToken.token);
      index = stringToken.nextIndex;
      continue;
    }
    if (isProjectConfigIdentifierStart(character)) {
      const start = index;
      index += 1;
      while (
        index < source.length &&
        isProjectConfigIdentifierPart(source[index] as string)
      ) {
        index += 1;
      }
      tokens.push({
        kind: "identifier",
        value: source.slice(start, index),
      });
      continue;
    }
    if (/[0-9]/.test(character)) {
      const start = index;
      index += 1;
      while (
        index < source.length &&
        /[A-Za-z0-9_.]/.test(source[index] ?? "")
      ) {
        index += 1;
      }
      tokens.push({
        kind: "number",
        value: source.slice(start, index),
      });
      continue;
    }
    if (source.startsWith("...", index)) {
      tokens.push({ kind: "punctuation", value: "..." });
      index += 3;
      continue;
    }
    tokens.push({ kind: "punctuation", value: character });
    index += 1;
  }
  return { tokens };
}

function readProjectConfigString(
  source: string,
  startIndex: number,
  quote: '"' | "'",
):
  | {
      token: ProjectConfigToken;
      nextIndex: number;
    }
  | {
      error: string;
    } {
  let index = startIndex + 1;
  let escaped = false;
  let value = "";
  while (index < source.length) {
    const character = source[index];
    if (character === quote) {
      return {
        token: {
          kind: "string",
          value,
          ...(escaped ? { escaped: true } : {}),
        },
        nextIndex: index + 1,
      };
    }
    if (character === "\n" || character === "\r") {
      return {
        error: "the project config contains an unterminated string literal.",
      };
    }
    if (character === "\\") {
      escaped = true;
      if (index + 1 >= source.length) {
        return {
          error: "the project config contains an unterminated string literal.",
        };
      }
      value += source.slice(index, index + 2);
      index += 2;
      continue;
    }
    value += character;
    index += 1;
  }
  return {
    error: "the project config contains an unterminated string literal.",
  };
}

function getProjectConfigClosingToken(value: string): string | undefined {
  if (value === "(") return ")";
  if (value === "[") return "]";
  if (value === "{") return "}";
  return undefined;
}

function isProjectConfigIdentifierStart(value: string): boolean {
  return /[$A-Z_a-z]/.test(value);
}

function isProjectConfigIdentifierPart(value: string): boolean {
  return /[$0-9A-Z_a-z]/.test(value);
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function asciiLowerCase(value: string): string {
  return value.replace(/[A-Z]/g, (character) => character.toLowerCase());
}

async function statIfExists(file: string) {
  try {
    return await fs.lstat(file);
  } catch (error) {
    if (hasNodeErrorCode(error, "ENOENT")) return undefined;
    throw error;
  }
}

function hasNodeErrorCode(error: unknown, code: string): boolean {
  return (
    Boolean(error) &&
    typeof error === "object" &&
    (error as { code?: unknown }).code === code
  );
}

function resolveProjectFile(cwd: string, file: string): string {
  const resolved = path.resolve(cwd, file);
  if (!isPathInside(cwd, resolved)) {
    throw new Error(`Migration path resolves outside project root: ${file}`);
  }
  return resolved;
}

function isPathInside(directory: string, candidate: string): boolean {
  const relative = path.relative(directory, candidate);
  return (
    relative === "" ||
    (!relative.startsWith(`..${path.sep}`) &&
      relative !== ".." &&
      !path.isAbsolute(relative))
  );
}

function toProjectPath(cwd: string, file: string): string {
  const relative = normalizePath(path.relative(cwd, file));
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function toRoutingDir(cwd: string, pagesDir: string): string {
  return normalizePath(path.relative(cwd, pagesDir)) || ".";
}

function normalizePath(value: string): string {
  return value.replaceAll(path.sep, "/");
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
