import fs from "node:fs/promises";
import path from "node:path";
import type { PageRouteNode } from "@evjs/shared/manifest";
import {
  findPageRouteSegmentConventionViolation,
  formatPageRouteSegmentConventionViolation,
  isIgnoredPageRouteSegment,
  isPageRouteSourceModuleFile,
  PAGE_ROUTE_ROOT_LAYOUT_ALIAS_FILES,
  PAGE_ROUTE_ROOT_LAYOUT_FILE,
  PAGE_ROUTE_SOURCE_EXTENSION_LABEL,
  parsePageRouteFile,
  routePathFromSegments,
  routeShapeFromSegments,
} from "./page-route-conventions.js";
import { sortPageRoutes } from "./page-route-order.js";
import {
  getParseErrorMessage,
  hasDefaultExport,
  parseRouteModuleWithError,
} from "./routes/shared.js";
import { deriveRouteIdFromPath } from "./utils.js";

export interface DiscoverPageRoutesOptions {
  dir: string;
  rootLayout?: boolean | string;
  required?: boolean;
}

export interface PageRouteDiscoveryDiagnostic {
  level: "warning" | "error";
  message: string;
  file?: string;
}

export interface PageRouteDiscovery {
  routes: PageRouteNode[];
  rootModule?: string;
  files: string[];
  diagnostics: PageRouteDiscoveryDiagnostic[];
}

export async function discoverPageRoutes(
  cwd: string,
  options: DiscoverPageRoutesOptions,
): Promise<PageRouteDiscovery> {
  const absoluteDir = path.resolve(cwd, options.dir);
  const diagnostics: PageRouteDiscoveryDiagnostic[] = [];
  const validDirectory = await validatePageRouteDirectory(
    cwd,
    absoluteDir,
    options.required === true,
    diagnostics,
  );
  if (!validDirectory) {
    return {
      routes: [],
      files: [],
      diagnostics,
    };
  }

  const files = await collectSourceFiles(cwd, absoluteDir);
  const pageLayoutDirectories = await collectPageLayoutDirectories(
    cwd,
    absoluteDir,
  );
  const pageLayoutDirectoriesWithSourceFiles = new Set<string>();
  const routes: PageRouteNode[] = [];
  const routeByPath = new Map<string, string>();
  const routeByShape = new Map<string, { file: string; path: string }>();
  const routeById = new Map<string, { file: string; path: string }>();
  let hasRouteCandidate = false;

  for (const file of files) {
    const sourceRel = toProjectPath(cwd, file);
    const routeRel = toPosixPath(path.relative(absoluteDir, file));
    const routeFile = parsePageRouteFile(routeRel);
    if (routeFile?.segments.includes("layout")) {
      const layoutDirectory = getPageLayoutDirectory(absoluteDir, file);
      if (layoutDirectory) {
        pageLayoutDirectoriesWithSourceFiles.add(layoutDirectory);
      }
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(sourceRel),
        message: createPageLayoutDiagnostic(
          cwd,
          absoluteDir,
          options.rootLayout,
        ),
      });
      continue;
    }

    if (!routeFile) continue;
    hasRouteCandidate = true;

    const segmentViolation = findPageRouteSegmentConventionViolation(
      routeFile.segments,
    );
    if (segmentViolation) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(sourceRel),
        message: formatPageRouteSegmentConventionViolation(segmentViolation),
      });
      continue;
    }

    const routePath = routePathFromSegments(routeFile.segments);
    const validRouteModule = await validateDefaultExport(file, diagnostics, {
      file: sourceRel,
      parseError: "Page route module could not be parsed",
      missingDefaultExport: createPageRouteDefaultExportDiagnostic(),
    });
    if (!validRouteModule) continue;

    const previous = routeByPath.get(routePath);
    if (previous) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(sourceRel),
        message: createDuplicateRoutePathDiagnostic(routePath, previous),
      });
      continue;
    }

    routeByPath.set(routePath, sourceRel);
    const routeShape = routeShapeFromSegments(routeFile.segments);
    const previousShapeOwner = routeByShape.get(routeShape.key);
    if (previousShapeOwner) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(sourceRel),
        message: createAmbiguousRouteShapeDiagnostic(
          routeShape.label,
          routePath,
          previousShapeOwner,
        ),
      });
      continue;
    }
    routeByShape.set(routeShape.key, { file: sourceRel, path: routePath });

    const routeId = deriveRouteIdFromPath(routePath);
    const previousIdOwner = routeById.get(routeId);
    if (previousIdOwner) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(sourceRel),
        message: `Duplicate page route id "${routeId}" for path "${routePath}" also generated by ${previousIdOwner.file} (${previousIdOwner.path}). Rename one route file so generated route ids are unique.`,
      });
      continue;
    }

    routeById.set(routeId, { file: sourceRel, path: routePath });
    routes.push({
      id: routeId,
      path: routePath,
      module: sourceRel,
    });
  }

  for (const layoutDirectory of pageLayoutDirectories) {
    if (pageLayoutDirectoriesWithSourceFiles.has(layoutDirectory)) continue;
    diagnostics.push({
      level: "error",
      file: toDiagnosticPath(toProjectPath(cwd, layoutDirectory)),
      message: createPageLayoutDiagnostic(cwd, absoluteDir, options.rootLayout),
    });
  }

  let rootModule: string | undefined;
  if (hasRouteCandidate && options.rootLayout !== false) {
    rootModule =
      typeof options.rootLayout === "string"
        ? await discoverExplicitRootLayout(cwd, options.rootLayout, diagnostics)
        : await discoverRootLayout(cwd, absoluteDir, diagnostics);
  }

  return {
    routes: sortPageRoutes(routes),
    rootModule,
    files,
    diagnostics,
  };
}

async function validatePageRouteDirectory(
  cwd: string,
  absoluteRouteDir: string,
  required: boolean,
  diagnostics: PageRouteDiscoveryDiagnostic[],
): Promise<boolean> {
  const expected = toProjectPath(cwd, absoluteRouteDir);
  if (!isInsideCwd(cwd, absoluteRouteDir)) {
    if (required) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(expected),
        message: `Page route directory must be inside the project root. ${expected} is not supported.`,
      });
    }
    return false;
  }

  let stat: import("node:fs").Stats;
  try {
    stat = await fs.stat(absoluteRouteDir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    if (required) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(expected),
        message: `Page route directory not found: ${expected}.`,
      });
    }
    return false;
  }

  if (!stat.isDirectory()) {
    if (required) {
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(expected),
        message: `Page route directory must be a directory: ${expected}.`,
      });
    }
    return false;
  }

  return true;
}

function createPageLayoutDiagnostic(
  cwd: string,
  absoluteRouteDir: string,
  rootLayout: DiscoverPageRoutesOptions["rootLayout"],
): string {
  const routeDirectoryMessage =
    "Files or folders named layout inside the page route directory are not route pages.";
  if (rootLayout === false) {
    return `${routeDirectoryMessage} Root layout discovery is disabled for this routing mode; move shared wrappers outside the route directory and import them from page modules.`;
  }
  if (typeof rootLayout === "string") {
    return `${routeDirectoryMessage} The configured root layout is ${rootLayout}; do not also place layout files inside the route directory.`;
  }

  const expected = toProjectPath(
    cwd,
    path.join(path.dirname(absoluteRouteDir), PAGE_ROUTE_ROOT_LAYOUT_FILE),
  );
  return `Layout files must live at ${expected} for SPA auto-discovery. ${routeDirectoryMessage} Move shared wrappers outside the route directory, or configure routing.layout for a custom SPA layout module.`;
}

function createDuplicateRoutePathDiagnostic(
  routePath: string,
  previous: string,
): string {
  return [
    `Duplicate page route path "${routePath}" also declared by ${previous}.`,
    "Keep one page module per URL path; choose either a flat route file or a directory index route file.",
  ].join(" ");
}

function createPageRouteDefaultExportDiagnostic(): string {
  return "Page route modules must default-export a React component. Move non-route helpers under an underscore-prefixed file or folder.";
}

function createRootLayoutDefaultExportDiagnostic(): string {
  return "Root layout must default-export a React component.";
}

async function discoverExplicitRootLayout(
  cwd: string,
  layout: string,
  diagnostics: PageRouteDiscoveryDiagnostic[],
): Promise<string | undefined> {
  const absolute = path.resolve(cwd, layout);
  const expected = toProjectPath(cwd, absolute);
  if (!isInsideCwd(cwd, absolute)) {
    diagnostics.push({
      level: "error",
      file: layout,
      message: `Root layout must be inside the project root. ${layout} is not supported.`,
    });
    return undefined;
  }

  let stat: import("node:fs").Stats;
  try {
    stat = await fs.stat(absolute);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    diagnostics.push({
      level: "error",
      file: toDiagnosticPath(expected),
      message: `Root layout module not found: ${expected}.`,
    });
    return undefined;
  }
  if (!stat.isFile()) {
    diagnostics.push({
      level: "error",
      file: toDiagnosticPath(expected),
      message: `Root layout module must be a file: ${expected}.`,
    });
    return undefined;
  }
  if (!isPageRouteSourceModuleFile(path.basename(absolute))) {
    diagnostics.push({
      level: "error",
      file: toDiagnosticPath(expected),
      message: `Root layout module must be a source module using ${PAGE_ROUTE_SOURCE_EXTENSION_LABEL}; declaration, test, spec, story, client-only, and server-only files are not supported. ${expected} is not supported.`,
    });
    return undefined;
  }

  const validRootLayout = await validateDefaultExport(absolute, diagnostics, {
    file: expected,
    parseError: "Root layout module could not be parsed",
    missingDefaultExport: createRootLayoutDefaultExportDiagnostic(),
  });
  return validRootLayout ? expected : undefined;
}

async function discoverRootLayout(
  cwd: string,
  absoluteRouteDir: string,
  diagnostics: PageRouteDiscoveryDiagnostic[],
): Promise<string | undefined> {
  const appDir = path.dirname(absoluteRouteDir);
  if (!isInsideCwd(cwd, appDir)) return undefined;

  const absolute = path.join(appDir, PAGE_ROUTE_ROOT_LAYOUT_FILE);
  const expected = toProjectPath(cwd, absolute);

  for (const alias of PAGE_ROUTE_ROOT_LAYOUT_ALIAS_FILES) {
    const aliased = path.join(appDir, alias);
    const actual = toProjectPath(cwd, aliased);
    try {
      await fs.access(aliased);
      diagnostics.push({
        level: "error",
        file: toDiagnosticPath(actual),
        message: `Root layout auto-discovery only uses ${expected}. ${actual} is not supported. Move it to ${expected}, or configure routing.layout for a custom SPA layout module.`,
      });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    }
  }

  const stat = await statIfExists(absolute);
  if (!stat) return undefined;
  if (!stat.isFile()) {
    diagnostics.push({
      level: "error",
      file: toDiagnosticPath(expected),
      message: `Root layout module must be a file: ${expected}.`,
    });
    return undefined;
  }

  const validRootLayout = await validateDefaultExport(absolute, diagnostics, {
    file: expected,
    parseError: "Root layout module could not be parsed",
    missingDefaultExport: createRootLayoutDefaultExportDiagnostic(),
  });
  if (!validRootLayout) return undefined;
  return toProjectPath(cwd, absolute);
}

async function validateDefaultExport(
  absolute: string,
  diagnostics: PageRouteDiscoveryDiagnostic[],
  messages: {
    file: string;
    parseError: string;
    missingDefaultExport: string;
  },
): Promise<boolean> {
  const source = await fs.readFile(absolute, "utf-8");
  const { ast, error } = parseRouteModuleWithError(source);
  const file = toDiagnosticPath(messages.file);

  if (!ast) {
    diagnostics.push({
      level: "error",
      file,
      message: `${messages.parseError}: ${formatParseError(error)}`,
    });
    return false;
  }

  if (!hasDefaultExport(ast)) {
    diagnostics.push({
      level: "error",
      file,
      message: messages.missingDefaultExport,
    });
    return false;
  }

  return true;
}

function formatParseError(error: unknown): string {
  return (
    getParseErrorMessage(error).split("\n").find(Boolean)?.trim() ??
    "Unknown parse error."
  );
}

async function collectSourceFiles(cwd: string, dir: string): Promise<string[]> {
  const files: string[] = [];

  async function visit(current: string) {
    let entries: import("node:fs").Dirent[];
    try {
      entries = await fs.readdir(current, { withFileTypes: true });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return;
      throw err;
    }

    for (const entry of entries) {
      if (entry.name.startsWith(".")) continue;
      const absolute = path.join(current, entry.name);
      if (!isInsideCwd(cwd, absolute)) continue;
      if (entry.isDirectory()) {
        await visit(absolute);
        continue;
      }
      if (entry.isFile() && isPageRouteSourceModuleFile(entry.name)) {
        files.push(absolute);
      }
    }
  }

  await visit(dir);
  return files.sort();
}

async function collectPageLayoutDirectories(
  cwd: string,
  dir: string,
): Promise<string[]> {
  const directories: string[] = [];

  async function visit(current: string) {
    let entries: import("node:fs").Dirent[];
    try {
      entries = await fs.readdir(current, { withFileTypes: true });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return;
      throw err;
    }

    for (const entry of entries) {
      if (entry.name.startsWith(".")) continue;
      const absolute = path.join(current, entry.name);
      if (!entry.isDirectory() || !isInsideCwd(cwd, absolute)) continue;

      const routeSegments = toPosixPath(path.relative(dir, absolute))
        .split("/")
        .filter(Boolean);
      if (routeSegments.some(isIgnoredPageRouteSegment)) continue;

      if (entry.name === "layout") {
        directories.push(absolute);
        continue;
      }

      await visit(absolute);
    }
  }

  await visit(dir);
  return directories.sort();
}

function getPageLayoutDirectory(
  absoluteRouteDir: string,
  absoluteFile: string,
): string | undefined {
  const segments = toPosixPath(path.relative(absoluteRouteDir, absoluteFile))
    .split("/")
    .filter(Boolean);
  const layoutIndex = segments.indexOf("layout");
  if (layoutIndex === -1) return undefined;
  return path.join(absoluteRouteDir, ...segments.slice(0, layoutIndex + 1));
}

function createAmbiguousRouteShapeDiagnostic(
  routeShapeLabel: string,
  routePath: string,
  previous: { file: string; path: string },
): string {
  return [
    `Ambiguous page route shape "${routeShapeLabel}" for path "${routePath}"`,
    `also matches ${previous.file} (${previous.path}).`,
    "Use one dynamic param name for each URL shape or explicit pages config.",
  ].join(" ");
}

function toProjectPath(cwd: string, file: string): string {
  return `./${toPosixPath(path.relative(cwd, file))}`;
}

function toDiagnosticPath(projectPath: string): string {
  return projectPath.replace(/^\.\//, "");
}

function toPosixPath(value: string): string {
  return value.replaceAll(path.sep, "/").replaceAll("\\", "/");
}

async function statIfExists(
  file: string,
): Promise<import("node:fs").Stats | undefined> {
  try {
    return await fs.stat(file);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

function isInsideCwd(cwd: string, candidate: string): boolean {
  const relative = path.relative(cwd, candidate);
  return (
    relative === "" ||
    (!relative.startsWith("..") && !path.isAbsolute(relative))
  );
}
