import type { PageRouteNode } from "@evjs/shared/manifest";

export interface GeneratePageRouteTypesOptions {
  routes: PageRouteNode[];
  importBaseDir?: string;
  clientModule?: string;
}

export function generatePageRouteTypes({
  routes,
  importBaseDir,
  clientModule = "@evjs/client",
}: GeneratePageRouteTypesOptions): string {
  const sortedRoutes = [...routes].sort(compareRoutes);
  const routeTypes = sortedRoutes.map((route) => {
    const importName = createPageModuleIdentifier(route.id);
    return {
      ...route,
      typeImport: toTypeImportSpecifier(route.module, importBaseDir),
      importName,
      routeTypeName: createRouteTypeIdentifier(route.id),
    };
  });

  const imports = routeTypes.map(
    (route) =>
      `import type * as ${route.importName} from ${JSON.stringify(route.typeImport)};`,
  );

  const routeTypeDeclarations = routeTypes.map(
    (route) =>
      `  ${route.routeTypeName}: { id: ${JSON.stringify(route.id)}; path: ${JSON.stringify(route.path)}; module: typeof ${route.importName} };`,
  );

  return [
    "/* eslint-disable */",
    "// This file is generated by evjs. Do not edit it directly.",
    'import type { CreatePageRouteRegister } from "@evjs/client/internal/route-types";',
    ...imports,
    "",
    "interface EvPageRoutes {",
    ...routeTypeDeclarations,
    "}",
    "",
    `declare module ${JSON.stringify(clientModule)} {`,
    "  interface Register extends CreatePageRouteRegister<EvPageRoutes> {}",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

function compareRoutes(left: PageRouteNode, right: PageRouteNode): number {
  if (left.path === "/") return -1;
  if (right.path === "/") return 1;
  const leftDepth = left.path.split("/").length;
  const rightDepth = right.path.split("/").length;
  return leftDepth - rightDepth || left.path.localeCompare(right.path);
}

function createPageModuleIdentifier(routeId: string): string {
  return `EvPage_${toSafeIdentifier(routeId)}`;
}

function createRouteTypeIdentifier(routeId: string): string {
  return `EvRoute_${toSafeIdentifier(routeId)}`;
}

function toSafeIdentifier(value: string): string {
  const safe = value.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(safe) ? safe : `_${safe}`;
}

function toTypeImportSpecifier(module: string, importBaseDir?: string): string {
  const extensionless = module.replace(/\.[cm]?[jt]sx?$/, "");
  if (!importBaseDir || !module.startsWith("./")) return extensionless;

  const relative = pathRelative(importBaseDir, extensionless);
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function pathRelative(fromDir: string, module: string): string {
  const fromParts = fromDir.replace(/^\.\//, "").split("/").filter(Boolean);
  const moduleParts = module.replace(/^\.\//, "").split("/").filter(Boolean);

  while (
    fromParts.length > 0 &&
    moduleParts.length > 0 &&
    fromParts[0] === moduleParts[0]
  ) {
    fromParts.shift();
    moduleParts.shift();
  }

  return [...fromParts.map(() => ".."), ...moduleParts].join("/") || ".";
}
