export {
  type BrowserToTerminal,
  type ClientTarget,
  CONFIG_DEFAULTS,
  type Config,
  type ConfigPatch,
  type ConfigRoute,
  type ConfigRouteApplication,
  type ConfigRouteApplicationDocument,
  type CrossOriginLoadingPolicy,
  type DevConfig,
  type DevProxyPathRewrite,
  type DevProxyRule,
  defineConfig,
  definePageConfig,
  type ExtractInstalledPlugin,
  type InstalledPluginRegistry,
  type LoggingConfig,
  merge,
  type OutputConfig,
  type PageAnchorMetadata,
  type PageFileConfig,
  type PageFileDocumentConfig,
  type PageMetadata,
  type PagePluginOptions,
  type PagePluginOptionsCheck,
  type PageRouteDiscoveryMetadata,
  type PageRoutingConfig,
  type PageRoutingMode,
  type PolyfillConfig,
  type ResolvedConfig,
  type ResolvedConfigRoute,
  type ResolvedConfigRouteApplication,
  type ResolvedConfigRouteApplicationDocument,
  type ResolvedDevConfig,
  type ResolvedFrameworkConfig,
  type ResolvedLoggingConfig,
  type ResolvedOutputConfig,
  type ResolvedPageRoutingConfig,
  type ResolvedPolyfillConfig,
  type ResolvedServerConfig,
  type ResolvedServerConventionsConfig,
  type ResolvedServerDevConfig,
  type ResolvedServerExternalsConfig,
  type ResolvedServerResolveConfig,
  type ResolvedServerRscConfig,
  type ResolvedServerRuntimeConfig,
  type ResolvedTransportConfig,
  resolveBundlerConfig,
  resolveConfig,
  resolvePluginsConfig,
  type ServerConfig,
  type ServerDevConfig,
  type ServerExternalsConfig,
  type ServerResolveConfig,
  type ServerRscConfig,
  type StaticConfigCompatible,
  type StaticConfigObject,
  type StaticConfigValue,
  type TransportConfig,
} from "./resolution.js";
