/**
 * @evjs/shared/manifest
 *
 * Stable façade for control-plane contracts. Implementations live in focused
 * graph, page, and output domains so consumers do not depend on their layout.
 */

export type {
  StaticJsonObject,
  StaticJsonValue,
} from "../serialization/static-json.js";
export {
  type ApplicationWrapperSlotPlanItem,
  type AppOutput,
  type AppRouteLocation,
  type AppRouteTarget,
  type AssetGroup,
  assertFrameworkManifestShape,
  type BuildEntry,
  type BuildEntryMetadata,
  type BuildEntryOwner,
  type BuildEntryPhase,
  type BuildEnvironment,
  type BuildOutput,
  type BuildOutputPaths,
  type BuildPlan,
  type BuildPlanUpdate,
  type ClientContributionRuntime,
  type ClientEntrySlotPlanItem,
  type ClientReferenceNode,
  type ComponentModel,
  type ContributionRuntime,
  type ContributionTarget,
  type DeploymentDocumentOutput,
  type DeploymentMetadata,
  type DeploymentPageRenderOutput,
  type DeploymentRouteOutput,
  type DeploymentServerOutput,
  type DeploymentServerPageRenderOutput,
  type DevBuildPlan,
  type DevClientRoutePlan,
  type EntryContributionPosition,
  type FrameworkSlotName,
  type FrameworkSlotPlanItem,
  type GeneratedEntryPlan,
  type GeneratedFrameworkFilePlan,
  type GeneratedFrameworkPlan,
  type GeneratedImportEdgePlan,
  type GeneratedModulePlan,
  type GeneratedScope,
  type HtmlDocumentOutput,
  type HtmlPlan,
  type HtmlTagName,
  type HtmlTagPlacement,
  type HtmlTagSlotPlanItem,
  type HydrationMode,
  type PageOutput,
  type PageRenderingOutput,
  type PageRouteKind,
  type PageRouteNode,
  type PageScope,
  type PagesAppEntryMetadata,
  type PagesAppRouteNode,
  type PageWrapperSlotPlanItem,
  type PprCachePolicy,
  type PprConfig,
  type PprDeliveryMode,
  type PprPageOutput,
  type PprRegionConfig,
  type PprRegionOutput,
  type PrerenderConfig,
  type PublicPathOutput,
  type ReactComponentPageEntryMetadata,
  type ReactPageLayer,
  type ReactServerPageEntryMetadata,
  type RenderMode,
  type ResolveAliasSlotPlanItem,
  type ResolveExternalPlan,
  type ResolveExternalSlotPlanItem,
  type ResolvePlan,
  type RouteOutput,
  type RscBuildPlan,
  type RscOutput,
  type RscPageOutput,
  type RuntimeModuleOutput,
  type RuntimeOutput,
  type RuntimePlan,
  type RuntimeServerOutput,
  type ServerAppEntryMetadata,
  type ServerAppRouteNode,
  type ServerBuildPlan,
  type ServerDocumentPlan,
  type ServerDocumentShell,
  type ServerEntrySlotPlanItem,
  type ServerFunctionNode,
  type ServerFunctionOutput,
  type ServerMiddlewareNode,
  type ServerOutput,
  type ServerReferenceNode,
  type ServerRendererOutput,
  type ServerRenderPlan,
  type ServerRequestMiddlewareSlotPlanItem,
  type ServerResolvePlan,
  type ServerRouteNode,
  type ServerRouteOutput,
  type ServerRuntime,
  type TransportOutput,
} from "./contracts.js";
export {
  type ApplicationId,
  assertCoreGraph,
  assertPluginId,
  CONFIG_ROUTE_PROVIDER_ID,
  type CoreApplicationNode,
  type CoreApplicationPluginSetting,
  type CoreApplicationPluginSettings,
  type CoreClientRouteNode,
  type CoreClientRouteTarget,
  type CoreDocumentBootstrap,
  type CoreDocumentNode,
  type CoreDocumentOwner,
  type CoreGraph,
  type CoreNodeProvenance,
  type CorePageNode,
  type CorePagePluginSetting,
  type CorePagePluginSettings,
  type CorePageScope,
  type CorePageSource,
  type CorePluginApplicationContractSnapshot,
  type CorePluginCatalogEntrySnapshot,
  type CorePluginCatalogSnapshot,
  type CorePluginPageContractSnapshot,
  type CoreProvenanceProducer,
  type CoreRouteFacets,
  type CoreRouteLocation,
  type CoreRouteNode,
  type CoreRoutePattern,
  type CoreRouteSegment,
  type DocumentId,
  PAGE_ANCHOR_PROVIDER_ID,
  type PageId,
  type RouteId,
  resolveCorePageOwner,
} from "./graph/core.js";
export {
  coreRoutePatternShape,
  coreRoutePatternsEqual,
  isCoreRoutePatternPrefix,
} from "./graph/route-pattern.js";
export {
  assertPortableRelativeArtifactPath,
  assertPortableRelativeBrowserArtifactPath,
  canonicalPortableArtifactPathKey,
  portableArtifactPathsConflict,
} from "./output/artifact-path.js";
export {
  assertBuildOutputLinkInputClientAssets,
  type BuildOutputLinkInput,
  createDeploymentMetadata,
  type DeploymentMetadataOptions,
  linkBuildOutput,
} from "./output/linker.js";
export {
  assertBuildOutputServerArtifacts,
  assertServerRelativeArtifactPath,
  collectBuildOutputServerJavaScriptArtifacts,
} from "./output/server-artifacts.js";
export {
  assertPageMetadata,
  clonePageMetadata,
  type PageMetadata,
} from "./page/metadata.js";
