import fs from "node:fs";
import path from "node:path";
import { analyzeRoutes, resolveRoutes } from "@evjs/build-tools";
import type { ResolvedEvConfig } from "@evjs/ev";
import type { ConfigComplete, EntryOptions } from "@utoo/pack";
import fastGlob from "fast-glob";

export const CLIENT_ROUTE_MARKER = "__evRegisterClientRoute";
export const SERVER_ROUTE_MARKER = "__evRegisterServerRoute";

interface RouteMarkerFiles {
  clientMarker: string;
  serverMarker: string;
  entriesDir: string;
}

export interface PreparedRouteMarkers {
  entries: EntryOptions[];
  serverEntry?: string;
}

function encodeMarkerPayload(value: unknown): string {
  return Buffer.from(JSON.stringify(value), "utf-8").toString("base64");
}

function toPosixPath(value: string): string {
  return value.replaceAll(path.sep, "/");
}

function toImportSpecifier(
  fromFile: string,
  target: string,
  cwd: string,
): string {
  if (!path.isAbsolute(target) && !target.startsWith(".")) {
    return target;
  }

  const absoluteTarget = path.isAbsolute(target)
    ? target
    : path.resolve(cwd, target);
  let relative = toPosixPath(
    path.relative(path.dirname(fromFile), absoluteTarget),
  );
  if (!relative.startsWith(".")) {
    relative = `./${relative}`;
  }
  return relative;
}

function markerCall(markerName: string, payload: unknown): string {
  return `globalThis.${markerName}?.(${JSON.stringify(encodeMarkerPayload(payload))});`;
}

async function collectRouteMetadata(cwd: string) {
  const files = await fastGlob("src/**/*.{ts,tsx,js,jsx}", {
    cwd,
    absolute: true,
  });
  const clientRoutes = [];
  const serverRoutes = [];

  for (const file of files) {
    const source = await fs.promises.readFile(file, "utf-8");
    const analysis = analyzeRoutes(source);
    clientRoutes.push(...analysis.clientRoutes);
    serverRoutes.push(
      ...analysis.serverRoutes.map(({ path, methods }) => ({ path, methods })),
    );
  }

  return {
    clientRoutes: resolveRoutes(clientRoutes),
    serverRoutes,
  };
}

async function writeMarkerFiles(
  cwd: string,
  files: RouteMarkerFiles,
): Promise<void> {
  const { clientRoutes, serverRoutes } = await collectRouteMetadata(cwd);
  await fs.promises.mkdir(path.dirname(files.clientMarker), {
    recursive: true,
  });
  await fs.promises.mkdir(files.entriesDir, { recursive: true });

  const clientSource = [
    "/* generated by @evjs/bundler-utoopack */",
    ...clientRoutes.map((route) => markerCall(CLIENT_ROUTE_MARKER, route)),
    "export {};",
    "",
  ].join("\n");
  const serverSource = [
    "/* generated by @evjs/bundler-utoopack */",
    ...serverRoutes.map((route) => markerCall(SERVER_ROUTE_MARKER, route)),
    "export {};",
    "",
  ].join("\n");

  await fs.promises.writeFile(files.clientMarker, clientSource, "utf-8");
  await fs.promises.writeFile(files.serverMarker, serverSource, "utf-8");
}

async function writeClientEntryWrapper(
  files: RouteMarkerFiles,
  cwd: string,
  name: string,
  entry: string,
  includeName: boolean,
): Promise<EntryOptions> {
  const wrapper = path.join(files.entriesDir, `${name}.js`);
  const markerImport = toImportSpecifier(wrapper, files.clientMarker, cwd);
  const entryImport = toImportSpecifier(wrapper, entry, cwd);
  await fs.promises.writeFile(
    wrapper,
    [
      `import ${JSON.stringify(markerImport)};`,
      `import ${JSON.stringify(entryImport)};`,
      "",
    ].join("\n"),
    "utf-8",
  );
  return includeName ? { import: wrapper, name } : { import: wrapper };
}

async function writeServerEntryWrapper(
  files: RouteMarkerFiles,
  cwd: string,
  serverEntry: string,
): Promise<string> {
  const wrapper = path.join(files.entriesDir, "server.js");
  const markerImport = toImportSpecifier(wrapper, files.serverMarker, cwd);
  const entryImport = toImportSpecifier(wrapper, serverEntry, cwd);
  await fs.promises.writeFile(
    wrapper,
    [
      `import ${JSON.stringify(markerImport)};`,
      `export { default } from ${JSON.stringify(entryImport)};`,
      "",
    ].join("\n"),
    "utf-8",
  );
  return wrapper;
}

export async function prepareRouteMarkers(
  config: ResolvedEvConfig<ConfigComplete>,
  cwd: string,
  serverEntry: string | undefined,
): Promise<PreparedRouteMarkers> {
  const markerDir = path.resolve(cwd, ".evjs/utoopack");
  const files: RouteMarkerFiles = {
    clientMarker: path.join(markerDir, "client-routes.js"),
    serverMarker: path.join(markerDir, "server-routes.js"),
    entriesDir: path.join(markerDir, "entries"),
  };

  await writeMarkerFiles(cwd, files);

  const entries = config.pages
    ? await Promise.all(
        Object.entries(config.pages).map(([name, page]) =>
          writeClientEntryWrapper(
            files,
            cwd,
            name,
            path.resolve(cwd, page.entry),
            true,
          ),
        ),
      )
    : [
        await writeClientEntryWrapper(
          files,
          cwd,
          "main",
          path.resolve(cwd, config.entry),
          false,
        ),
      ];

  return {
    entries,
    serverEntry: serverEntry
      ? await writeServerEntryWrapper(files, cwd, serverEntry)
      : undefined,
  };
}
