import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { inspectFrameworkBuild } from "@evjs/ev/_internal/build";
import { afterEach, describe, expect, it } from "vitest";
import {
  formatSmallfishMigrationResult,
  migrateSmallfishProject,
} from "../src/migrate-smallfish.js";

const tempDirs: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirs
      .splice(0)
      .map((dir) => fs.rm(dir, { recursive: true, force: true })),
  );
});

describe("Smallfish migration", () => {
  it("defaults to a read-only source migration preview", async () => {
    const cwd = await createFixture({
      "src/pages/index/index.tsx":
        "export default function IndexPage() { return null; }",
      "src/pages/index/config.json": JSON.stringify({
        title: "Index Page",
      }),
      "src/pages/index/model.ts": "export const model = {};",
      "src/pages/index/components/index.ts": "export { Card } from './Card';",
      "src/pages/index/components/Card.tsx":
        "export function Card() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd });

    expect(result).toMatchObject({
      pagesDir: "./src/pages",
      routingDir: "src/pages",
      applied: false,
      diagnostics: [],
      documentAliases: [],
    });
    expect(result.changes).toEqual([
      {
        kind: "write",
        file: "./src/pages/page.tsx",
        content:
          '// Generated by ev migrate smallfish.\nexport { default } from "./index/index";\nexport * from "./index/index";\n',
      },
      {
        kind: "write",
        file: "./src/pages/page.config.ts",
        content: expect.stringContaining('title: "Index Page"'),
      },
      {
        kind: "delete",
        file: "./src/pages/index/config.json",
      },
    ]);
    await expectPathExists(path.join(cwd, "src/pages/index/index.tsx"));
    await expectPathMissing(path.join(cwd, "src/pages/page.tsx"));
    await expectPathExists(path.join(cwd, "src/pages/index/model.ts"));
    await expectPathExists(
      path.join(cwd, "src/pages/index/components/index.ts"),
    );

    expect(formatSmallfishMigrationResult(result)).toContain(
      "Run with --write to apply these source changes.",
    );
  });

  it("adds a thin Page anchor, converts metadata, and preserves imports", async () => {
    const pageSource =
      "export default function TodosPage() { return <main />; }";
    const privateSource = "export const todoStore = new Map();";
    const cwd = await createFixture({
      "src/pages/todos/index.tsx": pageSource,
      "src/pages/todos/config.json": JSON.stringify({
        title: "Todos",
        head: [
          [
            "meta",
            {
              name: "description",
              content: "Todo list",
            },
          ],
          ["meta", { name: "theme-color", content: "#fff" }, ""],
        ],
      }),
      "src/pages/todos/store.ts": privateSource,
      "src/pages/todos/components/index.ts": "export { Todo } from './Todo';",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(true);
    expect(result.diagnostics).toEqual([]);
    await expect(
      fs.readFile(path.join(cwd, "src/pages/todos/index.tsx"), "utf-8"),
    ).resolves.toBe(pageSource);
    await expectPathMissing(path.join(cwd, "src/pages/todos/config.json"));
    await expect(
      fs.readFile(path.join(cwd, "src/pages/todos/page.tsx"), "utf-8"),
    ).resolves.toBe(
      '// Generated by ev migrate smallfish.\nexport { default } from "./index";\nexport * from "./index";\n',
    );
    await expect(
      fs.readFile(path.join(cwd, "src/pages/todos/store.ts"), "utf-8"),
    ).resolves.toBe(privateSource);
    await expectPathExists(
      path.join(cwd, "src/pages/todos/components/index.ts"),
    );
    const pageConfig = await fs.readFile(
      path.join(cwd, "src/pages/todos/page.config.ts"),
      "utf-8",
    );
    expect(pageConfig).toContain(
      'import { definePageConfig } from "@evjs/ev";',
    );
    expect(pageConfig).toContain('title: "Todos"');
    expect(pageConfig).toContain('"description": "Todo list"');
    expect(pageConfig).toContain('"theme-color": "#fff"');
    expect(pageConfig).toContain('aliases: [\n      "todos.html"\n    ]');
    expect(result.documentAliases).toEqual([
      {
        pageDirectory: "./src/pages/todos",
        canonicalFileName: "todos/index.html",
        legacyFileName: "todos.html",
      },
    ]);
  });

  it("maps static router and htmlFileExtension to a Document alias", async () => {
    const cwd = await createFixture({
      "src/pages/routed/index.tsx":
        "export default function Routed() { return null; }",
      "src/pages/routed/config.json": JSON.stringify({
        title: "Routed",
        router: "nested/home",
        htmlFileExtension: ".htm",
      }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(true);
    expect(result.diagnostics).toEqual([]);
    expect(result.documentAliases).toEqual([
      {
        pageDirectory: "./src/pages/routed",
        canonicalFileName: "routed/index.html",
        legacyFileName: "nested/home.htm",
      },
    ]);
    await expect(
      fs.readFile(path.join(cwd, "src/pages/routed/page.config.ts"), "utf-8"),
    ).resolves.toContain('"nested/home.htm"');
    await expectPathMissing(path.join(cwd, "src/pages/routed/config.json"));
  });

  it("keeps a migrated custom router idempotent", async () => {
    const cwd = await createFixture({
      "src/pages/routed/index.tsx":
        "export default function Routed() { return null; }",
      "src/pages/routed/config.json": JSON.stringify({
        router: "nested/home",
        htmlFileExtension: ".htm",
      }),
    });

    const first = await migrateSmallfishProject({ cwd, write: true });
    expect(first.applied).toBe(true);

    const resumed = await migrateSmallfishProject({ cwd, write: true });
    expect(resumed.applied).toBe(false);
    expect(resumed.diagnostics).toEqual([]);
    expect(resumed.changes).toEqual([]);
    await expect(
      fs.readFile(path.join(cwd, "src/pages/routed/page.config.ts"), "utf-8"),
    ).resolves.toContain('"nested/home.htm"');
    await expectPathExists(path.join(cwd, "src/pages/routed/index.tsx"));
  });

  it.each([
    ".js",
    ".css",
    ".json",
  ])("rejects non-HTML Document extension %s", async (htmlFileExtension) => {
    const cwd = await createFixture({
      "src/pages/routed/index.tsx":
        "export default function Routed() { return null; }",
      "src/pages/routed/config.json": JSON.stringify({
        htmlFileExtension,
      }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_PAGE_CONFIG",
        file: "./src/pages/routed/config.json",
        message: expect.stringContaining('exactly ".html" or ".htm"'),
      }),
    );
    await expectPathExists(path.join(cwd, "src/pages/routed/index.tsx"));
    await expectPathMissing(path.join(cwd, "src/pages/routed/page.tsx"));
  });

  it("creates an alias config when a Page has no legacy config", async () => {
    const cwd = await createFixture({
      "src/pages/healthy/index.tsx":
        "export default function Healthy() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(true);
    expect(result.diagnostics).toEqual([]);
    await expect(
      fs.readFile(path.join(cwd, "src/pages/healthy/page.config.ts"), "utf-8"),
    ).resolves.toContain('"healthy.html"');
  });

  it("resumes a non-root Page that was already renamed to page.*", async () => {
    const cwd = await createFixture({
      "src/pages/healthy/page.tsx":
        "export default function Healthy() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(true);
    expect(result.diagnostics).toEqual([]);
    expect(result.changes).toEqual([
      expect.objectContaining({
        kind: "write",
        file: "./src/pages/healthy/page.config.ts",
      }),
    ]);
    await expect(
      fs.readFile(path.join(cwd, "src/pages/healthy/page.config.ts"), "utf-8"),
    ).resolves.toContain('"healthy.html"');

    const resumed = await migrateSmallfishProject({ cwd, write: true });
    expect(resumed.applied).toBe(false);
    expect(resumed.diagnostics).toEqual([]);
    expect(resumed.changes).toEqual([]);
  });

  it("diagnoses an ambiguous src/pages/index/page.* partial migration", async () => {
    const cwd = await createFixture({
      "src/pages/index/page.tsx":
        "export default function AmbiguousIndex() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "AMBIGUOUS_ROOT_PAGE",
        file: "./src/pages/index",
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/page.tsx"));
  });

  it("recognizes a previously generated root anchor on resume", async () => {
    const cwd = await createFixture({
      "src/pages/index/index.tsx":
        "export default function Root() { return null; }",
      "src/pages/index/config.json": JSON.stringify({ title: "Root" }),
    });

    const first = await migrateSmallfishProject({ cwd, write: true });
    expect(first.applied).toBe(true);

    const resumed = await migrateSmallfishProject({ cwd, write: true });
    expect(resumed.applied).toBe(false);
    expect(resumed.diagnostics).toEqual([]);
    expect(resumed.changes).toEqual([]);
    await expectPathExists(path.join(cwd, "src/pages/index/index.tsx"));
    await expectPathExists(path.join(cwd, "src/pages/page.tsx"));
  });

  it("produces canonical Pages accepted by post-migration inspect", async () => {
    const cwd = await createFixture({
      "index.html": '<div id="app"></div>',
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
      "src/pages/home/config.json": JSON.stringify({ title: "Home" }),
    });

    const migration = await migrateSmallfishProject({ cwd, write: true });
    expect(migration.applied).toBe(true);

    const inspected = await inspectFrameworkBuild(
      { routing: { mode: "mpa" } },
      { cwd, runLifecycleHooks: false },
    );

    expect(
      inspected.diagnostics.filter(
        (diagnostic) => diagnostic.level === "error",
      ),
    ).toEqual([]);
    expect(inspected.graph.pages.home).toMatchObject({
      metadata: { title: "Home" },
      source: {
        module: "./src/pages/home/page.tsx",
        scope: { kind: "directory", root: "./src/pages/home" },
      },
    });
    expect(inspected.graph.documents.home).toMatchObject({
      owner: { kind: "page", pageId: "home" },
      output: "home/index.html",
      aliases: ["home.html"],
    });
  });

  it("bridges a named Page export into a canonical default export", async () => {
    const cwd = await createFixture({
      "package.json": JSON.stringify({ type: "module" }),
      "src/pages/home/index.js":
        "export const Page = () => null;\nexport const pageValue = 42;",
    });

    const migration = await migrateSmallfishProject({ cwd, write: true });

    expect(migration.applied).toBe(true);
    expect(migration.diagnostics).toEqual([]);
    const anchor = path.join(cwd, "src/pages/home/page.js");
    await expect(fs.readFile(anchor, "utf-8")).resolves.toBe(
      '// Generated by ev migrate smallfish.\nexport { Page as default } from "./index";\nexport * from "./index";\n',
    );

    const pageModule = await import(pathToFileURL(anchor).href);
    expect(pageModule.default).toBe(pageModule.Page);
    expect(pageModule.pageValue).toBe(42);

    const inspected = await inspectFrameworkBuild(
      { routing: { mode: "mpa" } },
      { cwd, runLifecycleHooks: false },
    );
    expect(
      inspected.diagnostics.filter(
        (diagnostic) => diagnostic.level === "error",
      ),
    ).toEqual([]);
    expect(inspected.graph.pages.home?.source.module).toBe(
      "./src/pages/home/page.js",
    );
  });

  it("fails closed when a Smallfish entry exports no Page component", async () => {
    const cwd = await createFixture({
      "src/pages/home/index.tsx": "export const helper = () => null;",
      "src/pages/home/config.json": JSON.stringify({ title: "Home" }),
    });

    const migration = await migrateSmallfishProject({ cwd, write: true });

    expect(migration.applied).toBe(false);
    expect(migration.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "INVALID_PAGE_ENTRY",
        file: "./src/pages/home/index.tsx",
        message: expect.stringContaining(
          'must export a default component or a named "Page" component',
        ),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
    await expectPathExists(path.join(cwd, "src/pages/home/config.json"));
  });

  it("blocks every write when dynamic router or unsupported config is present", async () => {
    const cwd = await createFixture({
      "src/pages/healthy/index.tsx":
        "export default function Healthy() { return null; }",
      "src/pages/routed/index.tsx":
        "export default function Routed() { return null; }",
      "src/pages/routed/config.json": JSON.stringify({
        title: "Routed",
        router: "users/:id",
      }),
      "src/pages/scripted/index.tsx":
        "export default function Scripted() { return null; }",
      "src/pages/scripted/config.json": JSON.stringify({
        scripts: ["/analytics.js"],
      }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          level: "error",
          code: "UNSUPPORTED_ROUTER",
          file: "./src/pages/routed/config.json",
        }),
        expect.objectContaining({
          level: "error",
          code: "UNSUPPORTED_PAGE_CONFIG",
          file: "./src/pages/scripted/config.json",
        }),
      ]),
    );
    await expectPathExists(path.join(cwd, "src/pages/healthy/index.tsx"));
    await expectPathMissing(path.join(cwd, "src/pages/healthy/page.tsx"));
  });

  it.each([
    "shop/home.",
    "/shop/home",
    "shop/home-",
  ])("rejects unsafe static router %s", async (router) => {
    const cwd = await createFixture({
      "src/pages/routed/index.tsx":
        "export default function Routed() { return null; }",
      "src/pages/routed/config.json": JSON.stringify({ router }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_ROUTER",
        file: "./src/pages/routed/config.json",
      }),
    );
    await expectPathExists(path.join(cwd, "src/pages/routed/index.tsx"));
  });

  it("preflights canonical output and alias collisions before every write", async () => {
    const cwd = await createFixture({
      "src/pages/index/index.tsx":
        "export default function Root() { return null; }",
      "src/pages/routed/index.tsx":
        "export default function Routed() { return null; }",
      "src/pages/routed/config.json": JSON.stringify({
        router: "index",
      }),
      "src/pages/healthy/index.tsx":
        "export default function Healthy() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "DOCUMENT_OUTPUT_CONFLICT",
        file: "./src/pages/routed",
        message: expect.stringContaining('alias "index.html"'),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/page.tsx"));
    await expectPathMissing(path.join(cwd, "src/pages/healthy/page.tsx"));
    await expectPathMissing(path.join(cwd, "src/pages/healthy/page.config.ts"));
  });

  it("preflights aliases that collide across migrated Pages", async () => {
    const cwd = await createFixture({
      "src/pages/foo/index.tsx":
        "export default function Foo() { return null; }",
      "src/pages/bar/index.tsx":
        "export default function Bar() { return null; }",
      "src/pages/bar/config.json": JSON.stringify({
        router: "foo",
      }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "DOCUMENT_OUTPUT_CONFLICT",
        message: expect.stringContaining('alias "foo.html"'),
      }),
    );
    await expectPathExists(path.join(cwd, "src/pages/foo/index.tsx"));
    await expectPathExists(path.join(cwd, "src/pages/bar/index.tsx"));
  });

  it("blocks a root migration when a canonical root anchor exists", async () => {
    const cwd = await createFixture({
      "src/pages/page.tsx":
        "export default function CanonicalRoot() { return null; }",
      "src/pages/index/index.tsx":
        "export default function SmallfishRoot() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "DUPLICATE_ENTRY",
        file: "./src/pages",
      }),
    );
    await expect(
      fs.readFile(path.join(cwd, "src/pages/page.tsx"), "utf-8"),
    ).resolves.toContain("CanonicalRoot");
    await expectPathExists(path.join(cwd, "src/pages/index/index.tsx"));
  });

  it("diagnoses duplicate index and page entry variants", async () => {
    const cwd = await createFixture({
      "src/pages/duplicate/index.ts":
        "export default function Page() { return null; }",
      "src/pages/duplicate/index.tsx":
        "export default function Page() { return null; }",
      "src/pages/duplicate/page.jsx":
        "export default function Page() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(
      result.diagnostics.filter(
        (diagnostic) => diagnostic.code === "DUPLICATE_ENTRY",
      ),
    ).toHaveLength(2);
    await expectPathExists(path.join(cwd, "src/pages/duplicate/index.ts"));
    await expectPathExists(path.join(cwd, "src/pages/duplicate/index.tsx"));
    await expectPathExists(path.join(cwd, "src/pages/duplicate/page.jsx"));
  });

  it.each([
    ["recursive Page", "src/pages/home/components/page.tsx"],
    ["layout facet", "src/pages/home/layout.tsx"],
    ["error facet", "src/pages/home/error.tsx"],
    ["not-found facet", "src/pages/home/not-found.tsx"],
    ["Page HTML template", "src/pages/home/index.html"],
  ])("blocks an existing %s activated by Core conventions", async (_label, file) => {
    const cwd = await createFixture({
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
      [file]: "export default function ExistingConvention() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNEXPECTED_CORE_CONVENTION",
        file: `./${file}`,
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
    await expectPathExists(path.join(cwd, "src/pages/home/index.tsx"));
  });

  it.each([
    "page.tsx",
    "page.config.ts",
    "config.json",
  ])("fails closed when migration candidate %s is a symlink", async (candidate) => {
    const cwd = await createFixture({
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });
    await fs.symlink("index.tsx", path.join(cwd, "src/pages/home", candidate));

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_SOURCE_FILE",
        file: `./src/pages/home/${candidate}`,
      }),
    );
    await expectPathExists(path.join(cwd, "src/pages/home/index.tsx"));
  });

  it("requires manual handling for explicit Smallfish pages", async () => {
    const cwd = await createFixture({
      "smallfish.config.ts": `
        export default {
          pages: [
            { name: "home", root: "pages/shared", entry: "home.tsx" },
            { name: "copy", root: "pages/shared", router: "landing" },
          ],
        };
      `,
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "EXPLICIT_PAGES",
        file: "./smallfish.config.ts",
      }),
    );
    await expectPathExists(path.join(cwd, "src/pages/home/index.tsx"));
  });

  it("recognizes deprecated baseDir as a custom Page root input", async () => {
    const cwd = await createFixture({
      "smallfish.config.ts": `export default { baseDir: "legacy" };`,
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "CUSTOM_PAGES_DIRECTORY",
        message: expect.stringContaining("baseDir"),
      }),
    );
  });

  it.each([
    "plugins",
    "presets",
  ])("fails closed when Smallfish %s can modify Page discovery", async (field) => {
    const cwd = await createFixture({
      "smallfish.config.ts": `export default { ${field}: [] };`,
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({
      cwd,
      pagesDir: "src/pages",
      write: true,
    });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_PROJECT_CONFIG",
        message: expect.stringContaining(field),
      }),
    );
  });

  it.each([
    "layout",
    "layoutsDir",
    "mountElementId",
    "globalStylesDir",
  ])("blocks Smallfish project field %s until Document semantics are migrated", async (field) => {
    const cwd = await createFixture({
      "smallfish.config.ts": `export default { ${field}: "custom" };`,
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_PROJECT_CONFIG",
        message: expect.stringContaining(field),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("blocks Smallfish's implicit global entry until it is imported explicitly", async () => {
    const cwd = await createFixture({
      "src/global.ts": "globalThis.__APP_READY__ = true;",
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_GLOBAL_SOURCE",
        file: "./src/global.ts",
        message: expect.stringContaining("automatically imports global.*"),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("blocks recursively injected Smallfish global styles", async () => {
    const cwd = await createFixture({
      "src/styles/base.css": "html { color: black; }",
      "src/styles/theme/dark.less": "body { background: black; }",
      "src/styles/README.md": "style notes",
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_GLOBAL_SOURCE",
        file: "./src/styles/base.css, ./src/styles/theme/dark.less",
        message: expect.stringContaining("automatically injects"),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("requires a shared root HTML template before writing anchors", async () => {
    const cwd = await createFixture({
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });
    await fs.rm(path.join(cwd, "index.html"));

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "MISSING_HTML_TEMPLATE",
        file: "./index.html",
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("requires the default mount in the shared root HTML template", async () => {
    const cwd = await createFixture({
      "index.html":
        '<!doctype html><html><head></head><body><main id="root"></main></body></html>',
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "INVALID_HTML_TEMPLATE",
        file: "./index.html",
        message: expect.stringContaining('mount "#app"'),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("fails closed when SMALLFISH_CUSTOM_CONFIG selects an environment override", async () => {
    const previous = process.env.SMALLFISH_CUSTOM_CONFIG;
    process.env.SMALLFISH_CUSTOM_CONFIG = "./config/production.ts";
    try {
      const cwd = await createFixture({
        "src/pages/home/index.tsx":
          "export default function Home() { return null; }",
      });

      const result = await migrateSmallfishProject({ cwd, write: true });

      expect(result.applied).toBe(false);
      expect(result.diagnostics).toContainEqual(
        expect.objectContaining({
          level: "error",
          code: "UNSUPPORTED_PROJECT_CONFIG",
          file: "SMALLFISH_CUSTOM_CONFIG",
        }),
      );
    } finally {
      if (previous === undefined) {
        delete process.env.SMALLFISH_CUSTOM_CONFIG;
      } else {
        process.env.SMALLFISH_CUSTOM_CONFIG = previous;
      }
    }
  });

  it.each([
    [
      "top-level shorthand",
      `
        const pages = [];
        export default { pages };
      `,
    ],
    [
      "top-level spread",
      `
        const shared = {};
        export default { ...shared };
      `,
    ],
    ["function export", "export default () => ({ mode: 'mobile' });"],
    ["computed property", "export default { ['pages']: [] };"],
    [
      "imported indirection",
      `
        import shared from "./shared";
        export default shared;
      `,
    ],
  ])("blocks unverifiable Smallfish project config using %s", async (_label, source) => {
    const cwd = await createFixture({
      "smallfish.config.ts": source,
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "UNSUPPORTED_PROJECT_CONFIG",
        file: "./smallfish.config.ts",
      }),
    );
    await expectPathExists(path.join(cwd, "src/pages/home/index.tsx"));
    await expectPathMissing(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("statically accepts a direct CommonJS object config", async () => {
    const cwd = await createFixture({
      "smallfish.config.cjs": `
        "use strict";
        module.exports = {
          publicPath: "/assets/",
        };
      `,
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(true);
    expect(result.diagnostics).toEqual([]);
    await expectPathExists(path.join(cwd, "src/pages/home/page.tsx"));
  });

  it("supports an explicitly resolved custom pages directory", async () => {
    const cwd = await createFixture({
      "smallfish.config.ts": `
        export default {
          appBaseDir: "app",
          pagesDir: "screens",
        };
      `,
      "app/screens/home/index.js":
        "export default function Home() { return null; }",
    });

    const withoutOverride = await migrateSmallfishProject({ cwd });
    expect(withoutOverride.diagnostics).toContainEqual(
      expect.objectContaining({
        code: "CUSTOM_PAGES_DIRECTORY",
      }),
    );

    const result = await migrateSmallfishProject({
      cwd,
      pagesDir: "app/screens",
      write: true,
    });
    expect(result.applied).toBe(true);
    expect(result.diagnostics).toEqual([]);
    expect(result.routingDir).toBe("app/screens");
    await expectPathExists(path.join(cwd, "app/screens/home/page.js"));
    await expectPathExists(path.join(cwd, "app/screens/home/index.js"));
  });

  it("rejects head entries that cannot map to named metadata", async () => {
    const cwd = await createFixture({
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
      "src/pages/home/config.json": JSON.stringify({
        head: [
          ["link", { rel: "icon", href: "/favicon.ico" }],
          ["meta", { property: "og:title", content: "Home" }],
        ],
      }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(
      result.diagnostics.filter(
        (diagnostic) => diagnostic.code === "UNSUPPORTED_HEAD",
      ),
    ).toHaveLength(2);
    await expectPathMissing(path.join(cwd, "src/pages/home/page.config.ts"));
    await expectPathExists(path.join(cwd, "src/pages/home/config.json"));
  });

  it.each([
    ["an empty name", [""], "must be non-empty"],
    [
      "surrounding whitespace",
      [" description "],
      "must not include leading or trailing whitespace",
    ],
    [
      "ASCII case-insensitive duplicates",
      ["Description", "description"],
      "ASCII case-insensitive",
    ],
    [
      "an unsafe __proto__ key",
      ["__proto__"],
      "is not a safe page.config.ts metadata key",
    ],
    [
      "an unsafe constructor key",
      ["constructor"],
      "is not a safe page.config.ts metadata key",
    ],
    [
      "an unsafe prototype key",
      ["prototype"],
      "is not a safe page.config.ts metadata key",
    ],
  ])("rejects named metadata with %s", async (_label, names, message) => {
    const cwd = await createFixture({
      "src/pages/home/index.tsx":
        "export default function Home() { return null; }",
      "src/pages/home/config.json": JSON.stringify({
        head: names.map((name) => [
          "meta",
          { name, content: `content for ${name}` },
        ]),
      }),
    });

    const result = await migrateSmallfishProject({ cwd, write: true });

    expect(result.applied).toBe(false);
    expect(result.diagnostics).toContainEqual(
      expect.objectContaining({
        level: "error",
        code: "INVALID_METADATA",
        file: "./src/pages/home/config.json",
        message: expect.stringContaining(message),
      }),
    );
    await expectPathMissing(path.join(cwd, "src/pages/home/page.config.ts"));
    await expectPathExists(path.join(cwd, "src/pages/home/config.json"));
  });
});

async function createFixture(files: Record<string, string>): Promise<string> {
  const cwd = await fs.mkdtemp(
    path.join(os.tmpdir(), "evjs-smallfish-migrate-"),
  );
  tempDirs.push(cwd);
  const fixtureFiles = {
    "index.html":
      '<!doctype html><html><head></head><body><main id="app"></main></body></html>',
    ...files,
  };
  for (const [file, source] of Object.entries(fixtureFiles)) {
    const absolute = path.join(cwd, file);
    await fs.mkdir(path.dirname(absolute), { recursive: true });
    await fs.writeFile(absolute, source, "utf-8");
  }
  return cwd;
}

async function expectPathExists(file: string): Promise<void> {
  await expect(fs.access(file)).resolves.toBeUndefined();
}

async function expectPathMissing(file: string): Promise<void> {
  await expect(fs.access(file)).rejects.toThrow();
}
